export interface StockMovement2 {
  /// <summary>
  /// STOJOU.VCRNUM_0
  /// </summary>
  DocNo?: string;
  /// <summary>
  /// STOJOU.VCRTYP_0
  /// </summary>
  MovementType?: string;
  /// <summary>
  /// STOJOU.IPTDAT_0
  /// </summary>
  MovementDate?: Date;
  MovementDateString?: string;
  /// <summary>
  /// STOJOU.QTYPCU_0
  /// </summary>
  QuantityIn?: number;
  QuantityInString?: string;
  /// <summary>
  /// STOJOU.QTYPCU_0
  /// </summary>
  QuantityOut?: number;
  QuantityOutString?: string;
  /// <summary>
  /// STOJOU.LOC_0
  /// </summary>
  Location?: string;
  /// <summary>
  /// STOJOU.CCE_1
  /// </summary>
  Bom?: string;
  /// <summary>
  /// STOJOU.CCE_2
  /// </summary>
  Project?: string;
  /// <summary>
  /// STOJOU.CCE_3
  /// </summary>
  WorkGroup?: string;
  Weight?: number;
}
