using System;
using System.Collections.Generic;

namespace VipcoSageX3.Models.SageX3
{
    public partial class Bank
    {
        public int Updtick0 { get; set; }
        public string Ban0 { get; set; }
        public byte Bancsh0 { get; set; }
        public string Des0 { get; set; }
        public string Dessho0 { get; set; }
        public short Nbrjou0 { get; set; }
        public byte Joutyp0 { get; set; }
        public byte Joutyp1 { get; set; }
        public byte Joutyp2 { get; set; }
        public byte Joutyp3 { get; set; }
        public byte Joutyp4 { get; set; }
        public byte Joutyp5 { get; set; }
        public byte Joutyp6 { get; set; }
        public byte Joutyp7 { get; set; }
        public byte Joutyp8 { get; set; }
        public byte Joutyp9 { get; set; }
        public string Jou0 { get; set; }
        public string Jou1 { get; set; }
        public string Jou2 { get; set; }
        public string Jou3 { get; set; }
        public string Jou4 { get; set; }
        public string Jou5 { get; set; }
        public string Jou6 { get; set; }
        public string Jou7 { get; set; }
        public string Jou8 { get; set; }
        public string Jou9 { get; set; }
        public string Gte0 { get; set; }
        public string Gte1 { get; set; }
        public string Gte2 { get; set; }
        public string Gte3 { get; set; }
        public string Gte4 { get; set; }
        public string Gte5 { get; set; }
        public string Gte6 { get; set; }
        public string Gte7 { get; set; }
        public string Gte8 { get; set; }
        public string Gte9 { get; set; }
        public string Treacc0 { get; set; }
        public string Treacc1 { get; set; }
        public string Treacc2 { get; set; }
        public string Treacc3 { get; set; }
        public string Treacc4 { get; set; }
        public string Treacc5 { get; set; }
        public string Treacc6 { get; set; }
        public string Treacc7 { get; set; }
        public string Treacc8 { get; set; }
        public string Treacc9 { get; set; }
        public string Coa0 { get; set; }
        public string Banacc0 { get; set; }
        public string Banbpr0 { get; set; }
        public byte Chgtyp0 { get; set; }
        public string Bidnum0 { get; set; }
        public string Bvrnum0 { get; set; }
        public string Pab10 { get; set; }
        public string Pab20 { get; set; }
        public byte Chqtypflg0 { get; set; }
        public byte Frmdudflg0 { get; set; }
        public byte Pabdudflg0 { get; set; }
        public decimal Deprat0 { get; set; }
        public string Acccod0 { get; set; }
        public string Sennum0 { get; set; }
        public string Biccod0 { get; set; }
        public string Ibacod0 { get; set; }
        public string Trecod0 { get; set; }
        public string Bantrm0 { get; set; }
        public DateTime Credat0 { get; set; }
        public string Creusr0 { get; set; }
        public DateTime Upddat0 { get; set; }
        public string Updusr0 { get; set; }
        public int Expnum0 { get; set; }
        public string Cpy0 { get; set; }
        public string Fcy0 { get; set; }
        public decimal Paytpy0 { get; set; }
        public string Addlig0 { get; set; }
        public string Addlig1 { get; set; }
        public string Addlig2 { get; set; }
        public string Poscod0 { get; set; }
        public string Cty0 { get; set; }
        public string Sat0 { get; set; }
        public string Cry0 { get; set; }
        public string Crynam0 { get; set; }
        public string Tel0 { get; set; }
        public string Fax0 { get; set; }
        public string Web0 { get; set; }
        public string Cur0 { get; set; }
        public string Filext0 { get; set; }
        public byte Reccpt0 { get; set; }
        public string Chkcod0 { get; set; }
        public string Acs0 { get; set; }
        public DateTime Chgdat0 { get; set; }
        public string Oldcur0 { get; set; }
        public string Crn0 { get; set; }
        public string Bidexs0 { get; set; }
        public string Curexs0 { get; set; }
        public byte Sctprolot0 { get; set; }
        public byte Chkfmt0 { get; set; }
        public string Nxtseq0 { get; set; }
        public byte Mcrprt0 { get; set; }
        public string Bantra0 { get; set; }
        public string Chkacc0 { get; set; }
        public string Pospayfil0 { get; set; }
        public byte Cfoexd0 { get; set; }
        public string Cce0 { get; set; }
        public string Cce1 { get; set; }
        public string Cce2 { get; set; }
        public string Cce3 { get; set; }
        public string Cce4 { get; set; }
        public string Cce5 { get; set; }
        public string Cce6 { get; set; }
        public string Cce7 { get; set; }
        public string Cce8 { get; set; }
        public string Cce9 { get; set; }
        public string Cce10 { get; set; }
        public string Cce11 { get; set; }
        public string Cce12 { get; set; }
        public string Cce13 { get; set; }
        public string Cce14 { get; set; }
        public string Cce15 { get; set; }
        public string Cce16 { get; set; }
        public string Cce17 { get; set; }
        public string Cce18 { get; set; }
        public string Cce19 { get; set; }
        public string Die0 { get; set; }
        public string Die1 { get; set; }
        public string Die2 { get; set; }
        public string Die3 { get; set; }
        public string Die4 { get; set; }
        public string Die5 { get; set; }
        public string Die6 { get; set; }
        public string Die7 { get; set; }
        public string Die8 { get; set; }
        public string Die9 { get; set; }
        public string Die10 { get; set; }
        public string Die11 { get; set; }
        public string Die12 { get; set; }
        public string Die13 { get; set; }
        public string Die14 { get; set; }
        public string Die15 { get; set; }
        public string Die16 { get; set; }
        public string Die17 { get; set; }
        public string Die18 { get; set; }
        public string Die19 { get; set; }
        public DateTime Credattim0 { get; set; }
        public DateTime Upddattim0 { get; set; }
        public byte[] Auuid0 { get; set; }
        public byte Bnkprobalctl0 { get; set; }
        public string Sennum20 { get; set; }
        public string Bvrcustid0 { get; set; }
        public string Banfil0 { get; set; }
        public string Bsirefban0 { get; set; }
        public decimal Rowid { get; set; }
    }
}
