using System;
using System.Collections.Generic;

namespace VipcoSageX3.Models.SageX3
{
    public partial class Bpcarrier
    {
        public int Updtick0 { get; set; }
        public string Bptnum0 { get; set; }
        public string Bptnam0 { get; set; }
        public string Bptsho0 { get; set; }
        public byte Pliflg0 { get; set; }
        public byte Bptplityp0 { get; set; }
        public decimal Tsdfre0 { get; set; }
        public decimal Tsdfre1 { get; set; }
        public decimal Tsdfre2 { get; set; }
        public decimal Tsdfre3 { get; set; }
        public decimal Tsdfre4 { get; set; }
        public string Weu0 { get; set; }
        public string Vou0 { get; set; }
        public decimal Coeweivol0 { get; set; }
        public decimal Fxdamt0 { get; set; }
        public decimal Bkt0 { get; set; }
        public decimal Adl0 { get; set; }
        public byte Weirnd0 { get; set; }
        public byte Ntrflg0 { get; set; }
        public string Bptfor0 { get; set; }
        public short Nbpli0 { get; set; }
        public decimal Plimax0 { get; set; }
        public decimal Plimax1 { get; set; }
        public decimal Plimax2 { get; set; }
        public decimal Plimax3 { get; set; }
        public decimal Plimax4 { get; set; }
        public decimal Plimax5 { get; set; }
        public decimal Plimax6 { get; set; }
        public decimal Plimax7 { get; set; }
        public decimal Plimax8 { get; set; }
        public decimal Plimax9 { get; set; }
        public decimal Plimax10 { get; set; }
        public decimal Plimax11 { get; set; }
        public decimal Plimax12 { get; set; }
        public decimal Plimax13 { get; set; }
        public decimal Plimax14 { get; set; }
        public decimal Plimax15 { get; set; }
        public decimal Plimax16 { get; set; }
        public decimal Plimax17 { get; set; }
        public decimal Plimax18 { get; set; }
        public decimal Plimax19 { get; set; }
        public decimal Plimax20 { get; set; }
        public decimal Plimax21 { get; set; }
        public decimal Plimax22 { get; set; }
        public decimal Plimax23 { get; set; }
        public decimal Plimax24 { get; set; }
        public decimal Plimax25 { get; set; }
        public decimal Plimax26 { get; set; }
        public decimal Plimax27 { get; set; }
        public decimal Plimax28 { get; set; }
        public decimal Plimax29 { get; set; }
        public decimal Plimax30 { get; set; }
        public decimal Plimax31 { get; set; }
        public decimal Plimax32 { get; set; }
        public decimal Plimax33 { get; set; }
        public decimal Plimax34 { get; set; }
        public decimal Plimax35 { get; set; }
        public decimal Plimax36 { get; set; }
        public decimal Plimax37 { get; set; }
        public decimal Plimax38 { get; set; }
        public decimal Plimax39 { get; set; }
        public decimal Plimax40 { get; set; }
        public decimal Plimax41 { get; set; }
        public decimal Plimax42 { get; set; }
        public decimal Plimax43 { get; set; }
        public decimal Plimax44 { get; set; }
        public decimal Plimax45 { get; set; }
        public decimal Plimax46 { get; set; }
        public decimal Plimax47 { get; set; }
        public decimal Plimax48 { get; set; }
        public decimal Plimax49 { get; set; }
        public decimal Plibkt0 { get; set; }
        public decimal Plibkt1 { get; set; }
        public decimal Plibkt2 { get; set; }
        public decimal Plibkt3 { get; set; }
        public decimal Plibkt4 { get; set; }
        public decimal Plibkt5 { get; set; }
        public decimal Plibkt6 { get; set; }
        public decimal Plibkt7 { get; set; }
        public decimal Plibkt8 { get; set; }
        public decimal Plibkt9 { get; set; }
        public decimal Plibkt10 { get; set; }
        public decimal Plibkt11 { get; set; }
        public decimal Plibkt12 { get; set; }
        public decimal Plibkt13 { get; set; }
        public decimal Plibkt14 { get; set; }
        public decimal Plibkt15 { get; set; }
        public decimal Plibkt16 { get; set; }
        public decimal Plibkt17 { get; set; }
        public decimal Plibkt18 { get; set; }
        public decimal Plibkt19 { get; set; }
        public decimal Plibkt20 { get; set; }
        public decimal Plibkt21 { get; set; }
        public decimal Plibkt22 { get; set; }
        public decimal Plibkt23 { get; set; }
        public decimal Plibkt24 { get; set; }
        public decimal Plibkt25 { get; set; }
        public decimal Plibkt26 { get; set; }
        public decimal Plibkt27 { get; set; }
        public decimal Plibkt28 { get; set; }
        public decimal Plibkt29 { get; set; }
        public decimal Plibkt30 { get; set; }
        public decimal Plibkt31 { get; set; }
        public decimal Plibkt32 { get; set; }
        public decimal Plibkt33 { get; set; }
        public decimal Plibkt34 { get; set; }
        public decimal Plibkt35 { get; set; }
        public decimal Plibkt36 { get; set; }
        public decimal Plibkt37 { get; set; }
        public decimal Plibkt38 { get; set; }
        public decimal Plibkt39 { get; set; }
        public decimal Plibkt40 { get; set; }
        public decimal Plibkt41 { get; set; }
        public decimal Plibkt42 { get; set; }
        public decimal Plibkt43 { get; set; }
        public decimal Plibkt44 { get; set; }
        public decimal Plibkt45 { get; set; }
        public decimal Plibkt46 { get; set; }
        public decimal Plibkt47 { get; set; }
        public decimal Plibkt48 { get; set; }
        public decimal Plibkt49 { get; set; }
        public decimal Pliuomrnd0 { get; set; }
        public decimal Pliuomrnd1 { get; set; }
        public decimal Pliuomrnd2 { get; set; }
        public decimal Pliuomrnd3 { get; set; }
        public decimal Pliuomrnd4 { get; set; }
        public decimal Pliuomrnd5 { get; set; }
        public decimal Pliuomrnd6 { get; set; }
        public decimal Pliuomrnd7 { get; set; }
        public decimal Pliuomrnd8 { get; set; }
        public decimal Pliuomrnd9 { get; set; }
        public decimal Pliuomrnd10 { get; set; }
        public decimal Pliuomrnd11 { get; set; }
        public decimal Pliuomrnd12 { get; set; }
        public decimal Pliuomrnd13 { get; set; }
        public decimal Pliuomrnd14 { get; set; }
        public decimal Pliuomrnd15 { get; set; }
        public decimal Pliuomrnd16 { get; set; }
        public decimal Pliuomrnd17 { get; set; }
        public decimal Pliuomrnd18 { get; set; }
        public decimal Pliuomrnd19 { get; set; }
        public decimal Pliuomrnd20 { get; set; }
        public decimal Pliuomrnd21 { get; set; }
        public decimal Pliuomrnd22 { get; set; }
        public decimal Pliuomrnd23 { get; set; }
        public decimal Pliuomrnd24 { get; set; }
        public decimal Pliuomrnd25 { get; set; }
        public decimal Pliuomrnd26 { get; set; }
        public decimal Pliuomrnd27 { get; set; }
        public decimal Pliuomrnd28 { get; set; }
        public decimal Pliuomrnd29 { get; set; }
        public decimal Pliuomrnd30 { get; set; }
        public decimal Pliuomrnd31 { get; set; }
        public decimal Pliuomrnd32 { get; set; }
        public decimal Pliuomrnd33 { get; set; }
        public decimal Pliuomrnd34 { get; set; }
        public decimal Pliuomrnd35 { get; set; }
        public decimal Pliuomrnd36 { get; set; }
        public decimal Pliuomrnd37 { get; set; }
        public decimal Pliuomrnd38 { get; set; }
        public decimal Pliuomrnd39 { get; set; }
        public decimal Pliuomrnd40 { get; set; }
        public decimal Pliuomrnd41 { get; set; }
        public decimal Pliuomrnd42 { get; set; }
        public decimal Pliuomrnd43 { get; set; }
        public decimal Pliuomrnd44 { get; set; }
        public decimal Pliuomrnd45 { get; set; }
        public decimal Pliuomrnd46 { get; set; }
        public decimal Pliuomrnd47 { get; set; }
        public decimal Pliuomrnd48 { get; set; }
        public decimal Pliuomrnd49 { get; set; }
        public string Cfy0 { get; set; }
        public string Cfy1 { get; set; }
        public string Cfy2 { get; set; }
        public string Cfy3 { get; set; }
        public string Cfy4 { get; set; }
        public string Cfy5 { get; set; }
        public string Cfy6 { get; set; }
        public string Cfy7 { get; set; }
        public string Cfy8 { get; set; }
        public string Cfy9 { get; set; }
        public string Cfy10 { get; set; }
        public string Cfy11 { get; set; }
        public string Cfy12 { get; set; }
        public string Cfy13 { get; set; }
        public string Cfy14 { get; set; }
        public string Cfy15 { get; set; }
        public string Cfy16 { get; set; }
        public string Cfy17 { get; set; }
        public string Cfy18 { get; set; }
        public string Cfy19 { get; set; }
        public string Cur0 { get; set; }
        public string Bpaadd0 { get; set; }
        public string Cntnam0 { get; set; }
        public int Expnum0 { get; set; }
        public string Scac0 { get; set; }
        public string Creusr0 { get; set; }
        public DateTime Credat0 { get; set; }
        public string Updusr0 { get; set; }
        public DateTime Upddat0 { get; set; }
        public DateTime Credattim0 { get; set; }
        public DateTime Upddattim0 { get; set; }
        public byte[] Auuid0 { get; set; }
        public decimal Rowid { get; set; }
    }
}
