using System;
using System.Collections.Generic;

namespace VipcoSageX3.Models.SageX3
{
    public partial class Bpsupplier
    {
        public int Updtick0 { get; set; }
        public string Bpsnum0 { get; set; }
        public string Bpsnam0 { get; set; }
        public string Bpssho0 { get; set; }
        public byte Bpstyp0 { get; set; }
        public string Bsgcod0 { get; set; }
        public string Bprpay0 { get; set; }
        public string Bpapay0 { get; set; }
        public string Bpsinv0 { get; set; }
        public string Bpainv0 { get; set; }
        public string Bpsgru0 { get; set; }
        public string Bpsrsk0 { get; set; }
        public string Bpcnumbps0 { get; set; }
        public string Bptnum0 { get; set; }
        public string Cntnam0 { get; set; }
        public string Loc0 { get; set; }
        public byte Abccls0 { get; set; }
        public string Uvycod0 { get; set; }
        public string Cur0 { get; set; }
        public byte Chgtyp0 { get; set; }
        public string Pte0 { get; set; }
        public string Dep0 { get; set; }
        public string Vacbpr0 { get; set; }
        public string Mdl0 { get; set; }
        public string Eecict0 { get; set; }
        public byte Eecloc0 { get; set; }
        public string Tsscod0 { get; set; }
        public string Tsscod1 { get; set; }
        public string Tsscod2 { get; set; }
        public string Tsscod3 { get; set; }
        public string Tsscod4 { get; set; }
        public decimal Invdtaamt0 { get; set; }
        public decimal Invdtaamt1 { get; set; }
        public decimal Invdtaamt2 { get; set; }
        public decimal Invdtaamt3 { get; set; }
        public decimal Invdtaamt4 { get; set; }
        public decimal Invdtaamt5 { get; set; }
        public decimal Invdtaamt6 { get; set; }
        public decimal Invdtaamt7 { get; set; }
        public decimal Invdtaamt8 { get; set; }
        public decimal Invdtaamt9 { get; set; }
        public decimal Invdtaamt10 { get; set; }
        public decimal Invdtaamt11 { get; set; }
        public decimal Invdtaamt12 { get; set; }
        public decimal Invdtaamt13 { get; set; }
        public decimal Invdtaamt14 { get; set; }
        public decimal Invdtaamt15 { get; set; }
        public decimal Invdtaamt16 { get; set; }
        public decimal Invdtaamt17 { get; set; }
        public decimal Invdtaamt18 { get; set; }
        public decimal Invdtaamt19 { get; set; }
        public decimal Invdtaamt20 { get; set; }
        public decimal Invdtaamt21 { get; set; }
        public decimal Invdtaamt22 { get; set; }
        public decimal Invdtaamt23 { get; set; }
        public decimal Invdtaamt24 { get; set; }
        public decimal Invdtaamt25 { get; set; }
        public decimal Invdtaamt26 { get; set; }
        public decimal Invdtaamt27 { get; set; }
        public decimal Invdtaamt28 { get; set; }
        public decimal Invdtaamt29 { get; set; }
        public short Invdta0 { get; set; }
        public short Invdta1 { get; set; }
        public short Invdta2 { get; set; }
        public short Invdta3 { get; set; }
        public short Invdta4 { get; set; }
        public short Invdta5 { get; set; }
        public short Invdta6 { get; set; }
        public short Invdta7 { get; set; }
        public short Invdta8 { get; set; }
        public short Invdta9 { get; set; }
        public short Invdta10 { get; set; }
        public short Invdta11 { get; set; }
        public short Invdta12 { get; set; }
        public short Invdta13 { get; set; }
        public short Invdta14 { get; set; }
        public short Invdta15 { get; set; }
        public short Invdta16 { get; set; }
        public short Invdta17 { get; set; }
        public short Invdta18 { get; set; }
        public short Invdta19 { get; set; }
        public short Invdta20 { get; set; }
        public short Invdta21 { get; set; }
        public short Invdta22 { get; set; }
        public short Invdta23 { get; set; }
        public short Invdta24 { get; set; }
        public short Invdta25 { get; set; }
        public short Invdta26 { get; set; }
        public short Invdta27 { get; set; }
        public short Invdta28 { get; set; }
        public short Invdta29 { get; set; }
        public byte Amtcod0 { get; set; }
        public byte Amtcod1 { get; set; }
        public byte Amtcod2 { get; set; }
        public byte Amtcod3 { get; set; }
        public byte Amtcod4 { get; set; }
        public byte Amtcod5 { get; set; }
        public byte Amtcod6 { get; set; }
        public byte Amtcod7 { get; set; }
        public byte Amtcod8 { get; set; }
        public byte Amtcod9 { get; set; }
        public byte Amtcod10 { get; set; }
        public byte Amtcod11 { get; set; }
        public byte Amtcod12 { get; set; }
        public byte Amtcod13 { get; set; }
        public byte Amtcod14 { get; set; }
        public byte Amtcod15 { get; set; }
        public byte Amtcod16 { get; set; }
        public byte Amtcod17 { get; set; }
        public byte Amtcod18 { get; set; }
        public byte Amtcod19 { get; set; }
        public byte Amtcod20 { get; set; }
        public byte Amtcod21 { get; set; }
        public byte Amtcod22 { get; set; }
        public byte Amtcod23 { get; set; }
        public byte Amtcod24 { get; set; }
        public byte Amtcod25 { get; set; }
        public byte Amtcod26 { get; set; }
        public byte Amtcod27 { get; set; }
        public byte Amtcod28 { get; set; }
        public byte Amtcod29 { get; set; }
        public string Plistc0 { get; set; }
        public string Payban0 { get; set; }
        public string Acccod0 { get; set; }
        public string Die0 { get; set; }
        public string Die1 { get; set; }
        public string Die2 { get; set; }
        public string Die3 { get; set; }
        public string Die4 { get; set; }
        public string Die5 { get; set; }
        public string Die6 { get; set; }
        public string Die7 { get; set; }
        public string Die8 { get; set; }
        public string Die9 { get; set; }
        public string Die10 { get; set; }
        public string Die11 { get; set; }
        public string Die12 { get; set; }
        public string Die13 { get; set; }
        public string Die14 { get; set; }
        public string Die15 { get; set; }
        public string Die16 { get; set; }
        public string Die17 { get; set; }
        public string Die18 { get; set; }
        public string Die19 { get; set; }
        public string Cce0 { get; set; }
        public string Cce1 { get; set; }
        public string Cce2 { get; set; }
        public string Cce3 { get; set; }
        public string Cce4 { get; set; }
        public string Cce5 { get; set; }
        public string Cce6 { get; set; }
        public string Cce7 { get; set; }
        public string Cce8 { get; set; }
        public string Cce9 { get; set; }
        public string Cce10 { get; set; }
        public string Cce11 { get; set; }
        public string Cce12 { get; set; }
        public string Cce13 { get; set; }
        public string Cce14 { get; set; }
        public string Cce15 { get; set; }
        public string Cce16 { get; set; }
        public string Cce17 { get; set; }
        public string Cce18 { get; set; }
        public string Cce19 { get; set; }
        public string Bpaadd0 { get; set; }
        public byte Sevlin0 { get; set; }
        public string Ordtex0 { get; set; }
        public string Rtntex0 { get; set; }
        public decimal Ltimrkcoe0 { get; set; }
        public decimal Primrkcoe0 { get; set; }
        public decimal Qlymrkcoe0 { get; set; }
        public decimal Qtymrkcoe0 { get; set; }
        public decimal Rskmrkcoe0 { get; set; }
        public decimal Ltimrk0 { get; set; }
        public decimal Primrk0 { get; set; }
        public decimal Qlymrk0 { get; set; }
        public decimal Qtymrk0 { get; set; }
        public decimal Rskmrk0 { get; set; }
        public decimal Genmrk0 { get; set; }
        public decimal Ordminamt0 { get; set; }
        public byte Ostctl0 { get; set; }
        public decimal Ostauzamt0 { get; set; }
        public decimal Eecincrat0 { get; set; }
        public string Bpsrem0 { get; set; }
        public byte Dudclc0 { get; set; }
        public byte Curclc0 { get; set; }
        public byte Fupflg0 { get; set; }
        public byte Ocnflg0 { get; set; }
        public byte Dadflg0 { get; set; }
        public string Prvnum0 { get; set; }
        public byte Douflg0 { get; set; }
        public byte Enaflg0 { get; set; }
        public byte Paylokflg0 { get; set; }
        public byte Norprnflg0 { get; set; }
        public byte Nreprnflg0 { get; set; }
        public byte Nrtprnflg0 { get; set; }
        public string Ritcod0 { get; set; }
        public short Ritnbr0 { get; set; }
        public decimal Ritrat0 { get; set; }
        public short Ritparnbr0 { get; set; }
        public string Ritparnam0 { get; set; }
        public decimal Ritparcoe0 { get; set; }
        public string Cai0 { get; set; }
        public DateTime Datvlycai0 { get; set; }
        public short Agtpcp0 { get; set; }
        public short Agtsattax0 { get; set; }
        public string Sattax0 { get; set; }
        public short Flgsattax0 { get; set; }
        public string Bpcnum0 { get; set; }
        public string Tpmcod0 { get; set; }
        public string Dia0 { get; set; }
        public string Iptexs0 { get; set; }
        public int Expnum0 { get; set; }
        public string Creusr0 { get; set; }
        public DateTime Credat0 { get; set; }
        public string Updusr0 { get; set; }
        public DateTime Upddat0 { get; set; }
        public string Mattol0 { get; set; }
        public byte Frm10990 { get; set; }
        public string Box10990 { get; set; }
        public DateTime Credattim0 { get; set; }
        public DateTime Upddattim0 { get; set; }
        public byte[] Auuid0 { get; set; }
        public byte Flg2810 { get; set; }
        public byte Purprityp0 { get; set; }
        public short Cshvat0 { get; set; }
        public DateTime Cshdat0 { get; set; }
        public string Autinvcod0 { get; set; }
        public decimal Ordfrefrt0 { get; set; }
        public string Ztaxbranch0 { get; set; }
        public string Zcompname0 { get; set; }
        public decimal Rowid { get; set; }
    }
}
