using System;
using System.Collections.Generic;

namespace VipcoSageX3.Models.SageX3
{
    public partial class Cacce
    {
        public int Updtick0 { get; set; }
        public string Cce0 { get; set; }
        public string Die0 { get; set; }
        public string Des0 { get; set; }
        public string Dessho0 { get; set; }
        public byte Enaflg0 { get; set; }
        public string Acs0 { get; set; }
        public string Fcy0 { get; set; }
        public DateTime Vlystr0 { get; set; }
        public DateTime Vlyend0 { get; set; }
        public string Auz0 { get; set; }
        public short Dienbr0 { get; set; }
        public string Othdie0 { get; set; }
        public string Othdie1 { get; set; }
        public string Othdie2 { get; set; }
        public string Othdie3 { get; set; }
        public string Othdie4 { get; set; }
        public string Othdie5 { get; set; }
        public string Othdie6 { get; set; }
        public string Othdie7 { get; set; }
        public string Othdie8 { get; set; }
        public string Othdie9 { get; set; }
        public string Othdie10 { get; set; }
        public string Othdie11 { get; set; }
        public string Othdie12 { get; set; }
        public string Othdie13 { get; set; }
        public string Othdie14 { get; set; }
        public string Othdie15 { get; set; }
        public string Othdie16 { get; set; }
        public string Othdie17 { get; set; }
        public string Othdie18 { get; set; }
        public string Othdie19 { get; set; }
        public string Defcce0 { get; set; }
        public string Defcce1 { get; set; }
        public string Defcce2 { get; set; }
        public string Defcce3 { get; set; }
        public string Defcce4 { get; set; }
        public string Defcce5 { get; set; }
        public string Defcce6 { get; set; }
        public string Defcce7 { get; set; }
        public string Defcce8 { get; set; }
        public string Defcce9 { get; set; }
        public string Defcce10 { get; set; }
        public string Defcce11 { get; set; }
        public string Defcce12 { get; set; }
        public string Defcce13 { get; set; }
        public string Defcce14 { get; set; }
        public string Defcce15 { get; set; }
        public string Defcce16 { get; set; }
        public string Defcce17 { get; set; }
        public string Defcce18 { get; set; }
        public string Defcce19 { get; set; }
        public short Uomnbr0 { get; set; }
        public string Uom0 { get; set; }
        public string Uom1 { get; set; }
        public string Uom2 { get; set; }
        public string Uom3 { get; set; }
        public string Uom4 { get; set; }
        public string Uom5 { get; set; }
        public string Uom6 { get; set; }
        public string Uom7 { get; set; }
        public string Uom8 { get; set; }
        public string Uom9 { get; set; }
        public string Uom10 { get; set; }
        public string Uom11 { get; set; }
        public string Uom12 { get; set; }
        public string Uom13 { get; set; }
        public string Uom14 { get; set; }
        public string Uom15 { get; set; }
        public string Uom16 { get; set; }
        public string Uom17 { get; set; }
        public string Uom18 { get; set; }
        public string Uom19 { get; set; }
        public decimal Qty0 { get; set; }
        public decimal Qty1 { get; set; }
        public decimal Qty2 { get; set; }
        public decimal Qty3 { get; set; }
        public decimal Qty4 { get; set; }
        public decimal Qty5 { get; set; }
        public decimal Qty6 { get; set; }
        public decimal Qty7 { get; set; }
        public decimal Qty8 { get; set; }
        public decimal Qty9 { get; set; }
        public decimal Qty10 { get; set; }
        public decimal Qty11 { get; set; }
        public decimal Qty12 { get; set; }
        public decimal Qty13 { get; set; }
        public decimal Qty14 { get; set; }
        public decimal Qty15 { get; set; }
        public decimal Qty16 { get; set; }
        public decimal Qty17 { get; set; }
        public decimal Qty18 { get; set; }
        public decimal Qty19 { get; set; }
        public byte Budtrk0 { get; set; }
        public byte Frw0 { get; set; }
        public byte Ipt0 { get; set; }
        public string Creusr0 { get; set; }
        public DateTime Credat0 { get; set; }
        public int Cretim0 { get; set; }
        public string Updusr0 { get; set; }
        public DateTime Upddat0 { get; set; }
        public int Updtim0 { get; set; }
        public int Expnum0 { get; set; }
        public DateTime Credattim0 { get; set; }
        public DateTime Upddattim0 { get; set; }
        public byte[] Auuid0 { get; set; }
        public decimal Rowid { get; set; }
    }
}
