using System;
using System.Collections.Generic;

namespace VipcoSageX3.Models.SageX3
{
    public partial class Facility
    {
        public int Updtick0 { get; set; }
        public string Fcy0 { get; set; }
        public string Fcynam0 { get; set; }
        public string Fcysho0 { get; set; }
        public string Cry0 { get; set; }
        public string Crn0 { get; set; }
        public string Naf0 { get; set; }
        public string Bptnum0 { get; set; }
        public byte Mfgflg0 { get; set; }
        public byte Salflg0 { get; set; }
        public byte Purflg0 { get; set; }
        public byte Wrhflg0 { get; set; }
        public byte Finflg0 { get; set; }
        public string Finrspfcy0 { get; set; }
        public byte Dadflg0 { get; set; }
        public string Payban0 { get; set; }
        public string Legcpy0 { get; set; }
        public string Leg0 { get; set; }
        public string Bpaadd0 { get; set; }
        public string Dadfcy0 { get; set; }
        public string Bidnum0 { get; set; }
        public string Cntnam0 { get; set; }
        public string Acccod0 { get; set; }
        public string Creusr0 { get; set; }
        public DateTime Credat0 { get; set; }
        public string Updusr0 { get; set; }
        public string Geocod0 { get; set; }
        public DateTime Upddat0 { get; set; }
        public DateTime Credattim0 { get; set; }
        public string Die0 { get; set; }
        public string Die1 { get; set; }
        public string Die2 { get; set; }
        public string Die3 { get; set; }
        public string Die4 { get; set; }
        public string Die5 { get; set; }
        public string Die6 { get; set; }
        public string Die7 { get; set; }
        public string Die8 { get; set; }
        public string Die9 { get; set; }
        public string Die10 { get; set; }
        public string Die11 { get; set; }
        public string Die12 { get; set; }
        public string Die13 { get; set; }
        public string Die14 { get; set; }
        public string Die15 { get; set; }
        public string Die16 { get; set; }
        public string Die17 { get; set; }
        public string Die18 { get; set; }
        public string Die19 { get; set; }
        public DateTime Upddattim0 { get; set; }
        public byte[] Auuid0 { get; set; }
        public string Insctyflg0 { get; set; }
        public string Cce0 { get; set; }
        public string Cce1 { get; set; }
        public string Cce2 { get; set; }
        public string Cce3 { get; set; }
        public string Cce4 { get; set; }
        public string Cce5 { get; set; }
        public string Cce6 { get; set; }
        public string Cce7 { get; set; }
        public string Cce8 { get; set; }
        public string Cce9 { get; set; }
        public string Cce10 { get; set; }
        public string Cce11 { get; set; }
        public string Cce12 { get; set; }
        public string Cce13 { get; set; }
        public string Cce14 { get; set; }
        public string Cce15 { get; set; }
        public string Cce16 { get; set; }
        public string Cce17 { get; set; }
        public string Cce18 { get; set; }
        public string Cce19 { get; set; }
        public byte Uvyday0 { get; set; }
        public byte Uvyday1 { get; set; }
        public byte Uvyday2 { get; set; }
        public byte Uvyday3 { get; set; }
        public byte Uvyday4 { get; set; }
        public byte Uvyday5 { get; set; }
        public byte Uvyday6 { get; set; }
        public string Uvycod0 { get; set; }
        public byte Ivyflg0 { get; set; }
        public string Ivyfcy0 { get; set; }
        public byte Wrhges0 { get; set; }
        public string Rcpwrh0 { get; set; }
        public string Mfpwrh0 { get; set; }
        public string Trawrh0 { get; set; }
        public string Rtnwrh0 { get; set; }
        public string Mfrwrh0 { get; set; }
        public string Shiwrh0 { get; set; }
        public string Mfgwrh0 { get; set; }
        public string Trfwrh0 { get; set; }
        public string Scowrh0 { get; set; }
        public string Sccwrh0 { get; set; }
        public short Spaopeigic0 { get; set; }
        public string Strhou0 { get; set; }
        public string Endhou0 { get; set; }
        public short Payflg0 { get; set; }
        public short Hrmdadflg0 { get; set; }
        public string Hrmdadfcy0 { get; set; }
        public string Bpasge0 { get; set; }
        public string Bpadcl0 { get; set; }
        public string Cntdds0 { get; set; }
        public string Codcra0 { get; set; }
        public short Regprh0 { get; set; }
        public string Prf0 { get; set; }
        public string Srv0 { get; set; }
        public string Cllcvt0 { get; set; }
        public string Rskwrk0 { get; set; }
        public string Hrmpayban0 { get; set; }
        public short Hrmtaxwag0 { get; set; }
        public short Secprh0 { get; set; }
        public short Flgapp0 { get; set; }
        public short Flgfor0 { get; set; }
        public short Flgpec0 { get; set; }
        public string Chef0 { get; set; }
        public decimal Rowid { get; set; }
    }
}
