using System;
using System.Collections.Generic;

namespace VipcoSageX3.Models.SageX3
{
    public partial class Gaccount
    {
        public int Updtick0 { get; set; }
        public string Coa0 { get; set; }
        public string Acc0 { get; set; }
        public string Des0 { get; set; }
        public string Dessho0 { get; set; }
        public byte Sac0 { get; set; }
        public string Accsho0 { get; set; }
        public string Csldeb0 { get; set; }
        public string Cslcdt0 { get; set; }
        public short Cslflg0 { get; set; }
        public byte Cslflgflw0 { get; set; }
        public string Flodeb0 { get; set; }
        public string Flocdt0 { get; set; }
        public string Clscod0 { get; set; }
        public string Cur0 { get; set; }
        public string Subacc0 { get; set; }
        public string Subbpr0 { get; set; }
        public string Rptcoddeb0 { get; set; }
        public string Rptcoddeb1 { get; set; }
        public string Rptcoddeb2 { get; set; }
        public string Rptcoddeb3 { get; set; }
        public string Rptcoddeb4 { get; set; }
        public string Rptcoddeb5 { get; set; }
        public string Rptcoddeb6 { get; set; }
        public string Rptcoddeb7 { get; set; }
        public string Rptcoddeb8 { get; set; }
        public string Rptcoddeb9 { get; set; }
        public string Rptcodcdt0 { get; set; }
        public string Rptcodcdt1 { get; set; }
        public string Rptcodcdt2 { get; set; }
        public string Rptcodcdt3 { get; set; }
        public string Rptcodcdt4 { get; set; }
        public string Rptcodcdt5 { get; set; }
        public string Rptcodcdt6 { get; set; }
        public string Rptcodcdt7 { get; set; }
        public string Rptcodcdt8 { get; set; }
        public string Rptcodcdt9 { get; set; }
        public byte Flguom0 { get; set; }
        public string Uom0 { get; set; }
        public decimal Valuom0 { get; set; }
        public byte Enaflg0 { get; set; }
        public string Acs0 { get; set; }
        public string Fcy0 { get; set; }
        public DateTime Vlystr0 { get; set; }
        public DateTime Vlyend0 { get; set; }
        public string Auz0 { get; set; }
        public short Coanbr0 { get; set; }
        public string Othcoa0 { get; set; }
        public string Othcoa1 { get; set; }
        public string Othcoa2 { get; set; }
        public string Othcoa3 { get; set; }
        public string Othcoa4 { get; set; }
        public string Othcoa5 { get; set; }
        public string Othcoa6 { get; set; }
        public string Othcoa7 { get; set; }
        public string Othcoa8 { get; set; }
        public string Othcoa9 { get; set; }
        public string Othcoa10 { get; set; }
        public string Othcoa11 { get; set; }
        public string Othcoa12 { get; set; }
        public string Othcoa13 { get; set; }
        public string Othcoa14 { get; set; }
        public string Othcoa15 { get; set; }
        public string Othcoa16 { get; set; }
        public string Othcoa17 { get; set; }
        public string Othcoa18 { get; set; }
        public string Othcoa19 { get; set; }
        public string Othcoa20 { get; set; }
        public string Othcoa21 { get; set; }
        public string Othcoa22 { get; set; }
        public string Othcoa23 { get; set; }
        public string Othcoa24 { get; set; }
        public string Othcoa25 { get; set; }
        public string Othcoa26 { get; set; }
        public string Othcoa27 { get; set; }
        public string Othcoa28 { get; set; }
        public string Othcoa29 { get; set; }
        public string Othcoa30 { get; set; }
        public string Othcoa31 { get; set; }
        public string Othcoa32 { get; set; }
        public string Othcoa33 { get; set; }
        public string Othcoa34 { get; set; }
        public string Othcoa35 { get; set; }
        public string Othcoa36 { get; set; }
        public string Othcoa37 { get; set; }
        public string Othcoa38 { get; set; }
        public string Othcoa39 { get; set; }
        public string Othcoa40 { get; set; }
        public string Othcoa41 { get; set; }
        public string Othcoa42 { get; set; }
        public string Othcoa43 { get; set; }
        public string Othcoa44 { get; set; }
        public string Othcoa45 { get; set; }
        public string Othcoa46 { get; set; }
        public string Othcoa47 { get; set; }
        public string Othcoa48 { get; set; }
        public string Othcoa49 { get; set; }
        public string Defacc0 { get; set; }
        public string Defacc1 { get; set; }
        public string Defacc2 { get; set; }
        public string Defacc3 { get; set; }
        public string Defacc4 { get; set; }
        public string Defacc5 { get; set; }
        public string Defacc6 { get; set; }
        public string Defacc7 { get; set; }
        public string Defacc8 { get; set; }
        public string Defacc9 { get; set; }
        public string Defacc10 { get; set; }
        public string Defacc11 { get; set; }
        public string Defacc12 { get; set; }
        public string Defacc13 { get; set; }
        public string Defacc14 { get; set; }
        public string Defacc15 { get; set; }
        public string Defacc16 { get; set; }
        public string Defacc17 { get; set; }
        public string Defacc18 { get; set; }
        public string Defacc19 { get; set; }
        public string Defacc20 { get; set; }
        public string Defacc21 { get; set; }
        public string Defacc22 { get; set; }
        public string Defacc23 { get; set; }
        public string Defacc24 { get; set; }
        public string Defacc25 { get; set; }
        public string Defacc26 { get; set; }
        public string Defacc27 { get; set; }
        public string Defacc28 { get; set; }
        public string Defacc29 { get; set; }
        public string Defacc30 { get; set; }
        public string Defacc31 { get; set; }
        public string Defacc32 { get; set; }
        public string Defacc33 { get; set; }
        public string Defacc34 { get; set; }
        public string Defacc35 { get; set; }
        public string Defacc36 { get; set; }
        public string Defacc37 { get; set; }
        public string Defacc38 { get; set; }
        public string Defacc39 { get; set; }
        public string Defacc40 { get; set; }
        public string Defacc41 { get; set; }
        public string Defacc42 { get; set; }
        public string Defacc43 { get; set; }
        public string Defacc44 { get; set; }
        public string Defacc45 { get; set; }
        public string Defacc46 { get; set; }
        public string Defacc47 { get; set; }
        public string Defacc48 { get; set; }
        public string Defacc49 { get; set; }
        public string Scracc0 { get; set; }
        public string Scracc1 { get; set; }
        public string Scracc2 { get; set; }
        public string Scracc3 { get; set; }
        public string Scracc4 { get; set; }
        public string Scracc5 { get; set; }
        public string Scracc6 { get; set; }
        public string Scracc7 { get; set; }
        public string Scracc8 { get; set; }
        public string Scracc9 { get; set; }
        public string Scracc10 { get; set; }
        public string Scracc11 { get; set; }
        public string Scracc12 { get; set; }
        public string Scracc13 { get; set; }
        public string Scracc14 { get; set; }
        public string Scracc15 { get; set; }
        public string Scracc16 { get; set; }
        public string Scracc17 { get; set; }
        public string Scracc18 { get; set; }
        public string Scracc19 { get; set; }
        public string Scracc20 { get; set; }
        public string Scracc21 { get; set; }
        public string Scracc22 { get; set; }
        public string Scracc23 { get; set; }
        public string Scracc24 { get; set; }
        public string Scracc25 { get; set; }
        public string Scracc26 { get; set; }
        public string Scracc27 { get; set; }
        public string Scracc28 { get; set; }
        public string Scracc29 { get; set; }
        public string Scracc30 { get; set; }
        public string Scracc31 { get; set; }
        public string Scracc32 { get; set; }
        public string Scracc33 { get; set; }
        public string Scracc34 { get; set; }
        public string Scracc35 { get; set; }
        public string Scracc36 { get; set; }
        public string Scracc37 { get; set; }
        public string Scracc38 { get; set; }
        public string Scracc39 { get; set; }
        public string Scracc40 { get; set; }
        public string Scracc41 { get; set; }
        public string Scracc42 { get; set; }
        public string Scracc43 { get; set; }
        public string Scracc44 { get; set; }
        public string Scracc45 { get; set; }
        public string Scracc46 { get; set; }
        public string Scracc47 { get; set; }
        public string Scracc48 { get; set; }
        public string Scracc49 { get; set; }
        public byte Obyipt0 { get; set; }
        public byte Obyipt1 { get; set; }
        public byte Obyipt2 { get; set; }
        public byte Obyipt3 { get; set; }
        public byte Obyipt4 { get; set; }
        public byte Obyipt5 { get; set; }
        public byte Obyipt6 { get; set; }
        public byte Obyipt7 { get; set; }
        public byte Obyipt8 { get; set; }
        public byte Obyipt9 { get; set; }
        public byte Obyipt10 { get; set; }
        public byte Obyipt11 { get; set; }
        public byte Obyipt12 { get; set; }
        public byte Obyipt13 { get; set; }
        public byte Obyipt14 { get; set; }
        public byte Obyipt15 { get; set; }
        public byte Obyipt16 { get; set; }
        public byte Obyipt17 { get; set; }
        public byte Obyipt18 { get; set; }
        public byte Obyipt19 { get; set; }
        public byte Obyipt20 { get; set; }
        public byte Obyipt21 { get; set; }
        public byte Obyipt22 { get; set; }
        public byte Obyipt23 { get; set; }
        public byte Obyipt24 { get; set; }
        public byte Obyipt25 { get; set; }
        public byte Obyipt26 { get; set; }
        public byte Obyipt27 { get; set; }
        public byte Obyipt28 { get; set; }
        public byte Obyipt29 { get; set; }
        public byte Obyipt30 { get; set; }
        public byte Obyipt31 { get; set; }
        public byte Obyipt32 { get; set; }
        public byte Obyipt33 { get; set; }
        public byte Obyipt34 { get; set; }
        public byte Obyipt35 { get; set; }
        public byte Obyipt36 { get; set; }
        public byte Obyipt37 { get; set; }
        public byte Obyipt38 { get; set; }
        public byte Obyipt39 { get; set; }
        public byte Obyipt40 { get; set; }
        public byte Obyipt41 { get; set; }
        public byte Obyipt42 { get; set; }
        public byte Obyipt43 { get; set; }
        public byte Obyipt44 { get; set; }
        public byte Obyipt45 { get; set; }
        public byte Obyipt46 { get; set; }
        public byte Obyipt47 { get; set; }
        public byte Obyipt48 { get; set; }
        public byte Obyipt49 { get; set; }
        public byte Flgvat0 { get; set; }
        public byte Vatipt0 { get; set; }
        public string Vat0 { get; set; }
        public string Vat1 { get; set; }
        public string Vat2 { get; set; }
        public byte Esdtrk0 { get; set; }
        public byte Snsdef0 { get; set; }
        public byte Snsblc0 { get; set; }
        public byte Mtc0 { get; set; }
        public byte Cen0 { get; set; }
        public byte Difflg0 { get; set; }
        public byte Dif0 { get; set; }
        public byte Losgaignr0 { get; set; }
        public byte Das0 { get; set; }
        public byte Dastyp0 { get; set; }
        public byte Flgabl0 { get; set; }
        public byte Flgexpcre0 { get; set; }
        public short Flgdep0 { get; set; }
        public string Gacpvs0 { get; set; }
        public byte Gacacn0 { get; set; }
        public short Rittyp0 { get; set; }
        public byte Updblc0 { get; set; }
        public byte Auzbpr0 { get; set; }
        public byte Auzbpr1 { get; set; }
        public byte Auzbpr2 { get; set; }
        public byte Auzbpr3 { get; set; }
        public byte Auzbpr4 { get; set; }
        public byte Auzbpr5 { get; set; }
        public byte Auzbpr6 { get; set; }
        public byte Auzbpr7 { get; set; }
        public byte Auzbpr8 { get; set; }
        public byte Auzbpr9 { get; set; }
        public string Dsp0 { get; set; }
        public short Dacdienbr0 { get; set; }
        public string Die0 { get; set; }
        public string Die1 { get; set; }
        public string Die2 { get; set; }
        public string Die3 { get; set; }
        public string Die4 { get; set; }
        public string Die5 { get; set; }
        public string Die6 { get; set; }
        public string Die7 { get; set; }
        public string Die8 { get; set; }
        public string Die9 { get; set; }
        public string Die10 { get; set; }
        public string Die11 { get; set; }
        public string Die12 { get; set; }
        public string Die13 { get; set; }
        public string Die14 { get; set; }
        public string Die15 { get; set; }
        public string Die16 { get; set; }
        public string Die17 { get; set; }
        public string Die18 { get; set; }
        public string Die19 { get; set; }
        public string Ccedef0 { get; set; }
        public string Ccedef1 { get; set; }
        public string Ccedef2 { get; set; }
        public string Ccedef3 { get; set; }
        public string Ccedef4 { get; set; }
        public string Ccedef5 { get; set; }
        public string Ccedef6 { get; set; }
        public string Ccedef7 { get; set; }
        public string Ccedef8 { get; set; }
        public string Ccedef9 { get; set; }
        public string Ccedef10 { get; set; }
        public string Ccedef11 { get; set; }
        public string Ccedef12 { get; set; }
        public string Ccedef13 { get; set; }
        public string Ccedef14 { get; set; }
        public string Ccedef15 { get; set; }
        public string Ccedef16 { get; set; }
        public string Ccedef17 { get; set; }
        public string Ccedef18 { get; set; }
        public string Ccedef19 { get; set; }
        public byte Budtrk0 { get; set; }
        public string Timdsp0 { get; set; }
        public byte Frwcur0 { get; set; }
        public string Bidnum0 { get; set; }
        public string Bpaadd0 { get; set; }
        public DateTime Upddat0 { get; set; }
        public DateTime Credat0 { get; set; }
        public int Updtim0 { get; set; }
        public int Cretim0 { get; set; }
        public string Updusr0 { get; set; }
        public string Creusr0 { get; set; }
        public int Expnum0 { get; set; }
        public DateTime Credattim0 { get; set; }
        public DateTime Upddattim0 { get; set; }
        public byte[] Auuid0 { get; set; }
        public byte Flg2810 { get; set; }
        public byte Typ2810 { get; set; }
        public byte Lvatyp0 { get; set; }
        public byte Typratflg0 { get; set; }
        public byte Typrat0 { get; set; }
        public string Cnvacc10 { get; set; }
        public string Cnvacc20 { get; set; }
        public string Cnvacc30 { get; set; }
        public string Cnvacc40 { get; set; }
        public byte Cslflgbpr0 { get; set; }
        public byte Cslbprace0 { get; set; }
        public string Cnvacc50 { get; set; }
        public string Cnvacc60 { get; set; }
        public string Cnvacc70 { get; set; }
        public string Cnvacc80 { get; set; }
        public string Cnvacc90 { get; set; }
        public string Cnvacc100 { get; set; }
        public byte Typvatctl0 { get; set; }
        public decimal Rowid { get; set; }
    }
}
