using System;
using System.Collections.Generic;

namespace VipcoSageX3.Models.SageX3
{
    public partial class Itmcateg
    {
        public int Updtick0 { get; set; }
        public string Tclcod0 { get; set; }
        public string Stofcy0 { get; set; }
        public string Tcldes0 { get; set; }
        public string Tclsho0 { get; set; }
        public byte Salflg0 { get; set; }
        public string Itmrefcou0 { get; set; }
        public byte Itmcremod0 { get; set; }
        public string Tsicod0 { get; set; }
        public string Tsicod1 { get; set; }
        public string Tsicod2 { get; set; }
        public string Tsicod3 { get; set; }
        public string Tsicod4 { get; set; }
        public string Die0 { get; set; }
        public string Die1 { get; set; }
        public string Die2 { get; set; }
        public string Die3 { get; set; }
        public string Die4 { get; set; }
        public string Die5 { get; set; }
        public string Die6 { get; set; }
        public string Die7 { get; set; }
        public string Die8 { get; set; }
        public string Die9 { get; set; }
        public string Die10 { get; set; }
        public string Die11 { get; set; }
        public string Die12 { get; set; }
        public string Die13 { get; set; }
        public string Die14 { get; set; }
        public string Die15 { get; set; }
        public string Die16 { get; set; }
        public string Die17 { get; set; }
        public string Die18 { get; set; }
        public string Die19 { get; set; }
        public string Cce0 { get; set; }
        public string Cce1 { get; set; }
        public string Cce2 { get; set; }
        public string Cce3 { get; set; }
        public string Cce4 { get; set; }
        public string Cce5 { get; set; }
        public string Cce6 { get; set; }
        public string Cce7 { get; set; }
        public string Cce8 { get; set; }
        public string Cce9 { get; set; }
        public string Cce10 { get; set; }
        public string Cce11 { get; set; }
        public string Cce12 { get; set; }
        public string Cce13 { get; set; }
        public string Cce14 { get; set; }
        public string Cce15 { get; set; }
        public string Cce16 { get; set; }
        public string Cce17 { get; set; }
        public string Cce18 { get; set; }
        public string Cce19 { get; set; }
        public string Acccod0 { get; set; }
        public byte Quaflg0 { get; set; }
        public string Quaacs0 { get; set; }
        public string Stu0 { get; set; }
        public string Puu0 { get; set; }
        public string Sau0 { get; set; }
        public string Ssu0 { get; set; }
        public string Eeu0 { get; set; }
        public decimal Puustucoe0 { get; set; }
        public decimal Saustucoe0 { get; set; }
        public decimal Ssustucoe0 { get; set; }
        public decimal Eeustucoe0 { get; set; }
        public byte Dacpuucoe0 { get; set; }
        public byte Dacsaucoe0 { get; set; }
        public string Weu0 { get; set; }
        public decimal Itmwei0 { get; set; }
        public string Vou0 { get; set; }
        public decimal Itmvou0 { get; set; }
        public string Pcu0 { get; set; }
        public string Pcu1 { get; set; }
        public string Pcu2 { get; set; }
        public string Pcu3 { get; set; }
        public decimal Pcustucoe0 { get; set; }
        public decimal Pcustucoe1 { get; set; }
        public decimal Pcustucoe2 { get; set; }
        public decimal Pcustucoe3 { get; set; }
        public byte Dacpcucoe0 { get; set; }
        public byte Dacpcucoe1 { get; set; }
        public byte Dacpcucoe2 { get; set; }
        public byte Dacpcucoe3 { get; set; }
        public byte Pcurul0 { get; set; }
        public byte Pcurul1 { get; set; }
        public byte Pcurul2 { get; set; }
        public byte Pcurul3 { get; set; }
        public string Lbefmt0 { get; set; }
        public string Lbefmt1 { get; set; }
        public string Lbefmt2 { get; set; }
        public string Lbefmt3 { get; set; }
        public string Stulbefmt0 { get; set; }
        public byte Stomgtcod0 { get; set; }
        public byte Stdflg0 { get; set; }
        public byte Negsto0 { get; set; }
        public byte Lotmgtcod0 { get; set; }
        public string Lotcou0 { get; set; }
        public byte Sermgtcod0 { get; set; }
        public string Sercou0 { get; set; }
        public byte Trkcod0 { get; set; }
        public byte Trklev0 { get; set; }
        public string Vltcod0 { get; set; }
        public byte Exymgtcod0 { get; set; }
        public string Exysta0 { get; set; }
        public byte Brdcod0 { get; set; }
        public string Plaacs0 { get; set; }
        public string Vacitm0 { get; set; }
        public string Vacitm1 { get; set; }
        public string Vacitm2 { get; set; }
        public byte Frthoruom0 { get; set; }
        public short Frthor0 { get; set; }
        public short Fimhor0 { get; set; }
        public byte Fimhoruom0 { get; set; }
        public decimal Ofs0 { get; set; }
        public string Buy0 { get; set; }
        public string Planner0 { get; set; }
        public decimal Minrmnprc0 { get; set; }
        public byte Rcpflg0 { get; set; }
        public byte Prqflg0 { get; set; }
        public decimal Cprcoe0 { get; set; }
        public decimal Cpramt0 { get; set; }
        public string Stcnum0 { get; set; }
        public byte Baspriori0 { get; set; }
        public decimal Purpriprc0 { get; set; }
        public string Cfglin0 { get; set; }
        public byte Locmgtcod0 { get; set; }
        public byte Locdes0 { get; set; }
        public byte Locdes1 { get; set; }
        public byte Locdes2 { get; set; }
        public byte Locdes3 { get; set; }
        public byte Locdes4 { get; set; }
        public byte Locdes5 { get; set; }
        public byte Locdes6 { get; set; }
        public byte Locdes7 { get; set; }
        public byte Locdes8 { get; set; }
        public byte Locdes9 { get; set; }
        public byte Locdes10 { get; set; }
        public byte Locdes11 { get; set; }
        public byte Locdes12 { get; set; }
        public byte Locdes13 { get; set; }
        public byte Locdes14 { get; set; }
        public string Allrulord0 { get; set; }
        public string Allrulmat0 { get; set; }
        public string Allrulshi0 { get; set; }
        public string Allrulmfg0 { get; set; }
        public string Allrultrf0 { get; set; }
        public string Allrulsco0 { get; set; }
        public string Allrulscc0 { get; set; }
        public string Allrulsre0 { get; set; }
        public byte Gloaaaflg0 { get; set; }
        public byte Gloqqqflg0 { get; set; }
        public byte Glorrrflg0 { get; set; }
        public byte Abccls0 { get; set; }
        public byte Stocod0 { get; set; }
        public byte Cuncod0 { get; set; }
        public string Sescod0 { get; set; }
        public decimal Shr0 { get; set; }
        public short Plh0 { get; set; }
        public byte Plhuot0 { get; set; }
        public short Foh0 { get; set; }
        public byte Fohuot0 { get; set; }
        public byte Reomgtcod0 { get; set; }
        public short Reoper0 { get; set; }
        public byte Reocod0 { get; set; }
        public string Reofcy0 { get; set; }
        public string Reopol0 { get; set; }
        public short Daycov0 { get; set; }
        public decimal Safsto0 { get; set; }
        public decimal Reotsd0 { get; set; }
        public decimal Maxsto0 { get; set; }
        public decimal Reominqty0 { get; set; }
        public decimal Mfglotqty0 { get; set; }
        public byte Otrstyp0 { get; set; }
        public byte Otrstyp1 { get; set; }
        public byte Otrstyp2 { get; set; }
        public byte Otrstyp3 { get; set; }
        public byte Otrstyp4 { get; set; }
        public string Ovecod0 { get; set; }
        public string Ovecod1 { get; set; }
        public string Ovecod2 { get; set; }
        public string Ovecod3 { get; set; }
        public string Ovecod4 { get; set; }
        public byte Ovecpnflg0 { get; set; }
        public byte Ovecpnflg1 { get; set; }
        public byte Ovecpnflg2 { get; set; }
        public byte Ovecpnflg3 { get; set; }
        public byte Ovecpnflg4 { get; set; }
        public byte Stdcstupd0 { get; set; }
        public byte Cutcstupd0 { get; set; }
        public byte Budcstupd0 { get; set; }
        public byte Simcstupd0 { get; set; }
        public byte Mfgshtcod0 { get; set; }
        public decimal Clepctaut0 { get; set; }
        public byte Itmtyp0 { get; set; }
        public decimal Salrmnprc0 { get; set; }
        public decimal Minqty0 { get; set; }
        public decimal Maxqty0 { get; set; }
        public byte Lndflg0 { get; set; }
        public byte Ctmflg0 { get; set; }
        public decimal Ctmqty0 { get; set; }
        public byte Purflg0 { get; set; }
        public byte Mfgflg0 { get; set; }
        public byte Scpflg0 { get; set; }
        public byte Scsflg0 { get; set; }
        public byte Phaflg0 { get; set; }
        public byte Genflg0 { get; set; }
        public byte Tooflg0 { get; set; }
        public byte Dlvflg0 { get; set; }
        public byte Intflg0 { get; set; }
        public byte Mceflg0 { get; set; }
        public string Pck0 { get; set; }
        public decimal Pckcap0 { get; set; }
        public string Ptocod0 { get; set; }
        public byte Pckstkflg0 { get; set; }
        public string Qlycrd0 { get; set; }
        public string Ordwrh0 { get; set; }
        public string Matwrh0 { get; set; }
        public string Shiwrh0 { get; set; }
        public string Mfgwrh0 { get; set; }
        public string Trfwrh0 { get; set; }
        public string Scowrh0 { get; set; }
        public string Sccwrh0 { get; set; }
        public string Srewrh0 { get; set; }
        public byte Flgfas0 { get; set; }
        public byte Pckflg0 { get; set; }
        public int Expnum0 { get; set; }
        public string Pcccod0 { get; set; }
        public DateTime Credat0 { get; set; }
        public string Creusr0 { get; set; }
        public DateTime Upddat0 { get; set; }
        public string Updusr0 { get; set; }
        public string Mattol0 { get; set; }
        public string Sstcod0 { get; set; }
        public DateTime Credattim0 { get; set; }
        public DateTime Upddattim0 { get; set; }
        public byte[] Auuid0 { get; set; }
        public byte Itmsfttyp0 { get; set; }
        public string Frtcls0 { get; set; }
        public string Nmfc0 { get; set; }
        public byte Eccflg0 { get; set; }
        public byte Eccsto0 { get; set; }
        public string Eccmin0 { get; set; }
        public string Eccmaj0 { get; set; }
        public byte Loaeccflg0 { get; set; }
        public string Invcnd0 { get; set; }
        public short Invprodtyp0 { get; set; }
        public decimal Rowid { get; set; }
    }
}
