using System;
using System.Collections.Generic;

namespace VipcoSageX3.Models.SageX3
{
    public partial class Itmfacilit
    {
        public int Updtick0 { get; set; }
        public string Itmref0 { get; set; }
        public string Stofcy0 { get; set; }
        public byte Cunflg0 { get; set; }
        public string Cunlisnum0 { get; set; }
        public byte Abccls0 { get; set; }
        public byte Locmgtcod0 { get; set; }
        public byte Stocod0 { get; set; }
        public byte Cuncod0 { get; set; }
        public string Sescod0 { get; set; }
        public short Daycov0 { get; set; }
        public decimal Totlti0 { get; set; }
        public decimal Qualti0 { get; set; }
        public short Plh0 { get; set; }
        public byte Plhuot0 { get; set; }
        public short Foh0 { get; set; }
        public byte Fohuot0 { get; set; }
        public decimal Ofs0 { get; set; }
        public decimal Mfglti0 { get; set; }
        public decimal Prplti0 { get; set; }
        public short Mic0 { get; set; }
        public byte Reomgtcod0 { get; set; }
        public short Reoper0 { get; set; }
        public byte Reocod0 { get; set; }
        public string Reofcy0 { get; set; }
        public string Reopol0 { get; set; }
        public decimal Safsto0 { get; set; }
        public decimal Safstoclc0 { get; set; }
        public decimal Reotsd0 { get; set; }
        public decimal Reotsdclc0 { get; set; }
        public decimal Maxsto0 { get; set; }
        public decimal Maxstoclc0 { get; set; }
        public decimal Reominqty0 { get; set; }
        public decimal Reominclc0 { get; set; }
        public decimal Mfglotqty0 { get; set; }
        public decimal Shr0 { get; set; }
        public string Planner0 { get; set; }
        public string Buy0 { get; set; }
        public byte Otrstyp0 { get; set; }
        public byte Otrstyp1 { get; set; }
        public byte Otrstyp2 { get; set; }
        public byte Otrstyp3 { get; set; }
        public byte Otrstyp4 { get; set; }
        public string Ovecod0 { get; set; }
        public string Ovecod1 { get; set; }
        public string Ovecod2 { get; set; }
        public string Ovecod3 { get; set; }
        public string Ovecod4 { get; set; }
        public byte Ovecpnflg0 { get; set; }
        public byte Ovecpnflg1 { get; set; }
        public byte Ovecpnflg2 { get; set; }
        public byte Ovecpnflg3 { get; set; }
        public byte Ovecpnflg4 { get; set; }
        public byte Stdcstupd0 { get; set; }
        public byte Cutcstupd0 { get; set; }
        public byte Budcstupd0 { get; set; }
        public byte Simcstupd0 { get; set; }
        public string Mfgrou0 { get; set; }
        public string Cstrou0 { get; set; }
        public string Rccrou0 { get; set; }
        public short Mfgroualt0 { get; set; }
        public short Cstroualt0 { get; set; }
        public short Rccroualt0 { get; set; }
        public byte Mfgshtcod0 { get; set; }
        public byte Relscatia0 { get; set; }
        public short Monproyea0 { get; set; }
        public short Monpromon0 { get; set; }
        public short Yeaproyea0 { get; set; }
        public decimal Clepctaut0 { get; set; }
        public string Cfgvcrnum0 { get; set; }
        public string Ism0 { get; set; }
        public string Wgracs0 { get; set; }
        public short Redmodflg0 { get; set; }
        public decimal Itmtolpos0 { get; set; }
        public decimal Itmtolneg0 { get; set; }
        public string Vltcod0 { get; set; }
        public decimal Proper0 { get; set; }
        public byte Locnum0 { get; set; }
        public byte Locnum1 { get; set; }
        public byte Locnum2 { get; set; }
        public byte Locnum3 { get; set; }
        public byte Locnum4 { get; set; }
        public byte Locnum5 { get; set; }
        public byte Locnum6 { get; set; }
        public byte Locnum7 { get; set; }
        public byte Locnum8 { get; set; }
        public byte Locnum9 { get; set; }
        public byte Locnum10 { get; set; }
        public byte Locnum11 { get; set; }
        public byte Locnum12 { get; set; }
        public byte Locnum13 { get; set; }
        public byte Locnum14 { get; set; }
        public string Defloctyp0 { get; set; }
        public string Defloctyp1 { get; set; }
        public string Defloctyp2 { get; set; }
        public string Defloctyp3 { get; set; }
        public string Defloctyp4 { get; set; }
        public string Defloctyp5 { get; set; }
        public string Defloctyp6 { get; set; }
        public string Defloctyp7 { get; set; }
        public string Defloctyp8 { get; set; }
        public string Defloctyp9 { get; set; }
        public string Defloctyp10 { get; set; }
        public string Defloctyp11 { get; set; }
        public string Defloctyp12 { get; set; }
        public string Defloctyp13 { get; set; }
        public string Defloctyp14 { get; set; }
        public string Defloc0 { get; set; }
        public string Defloc1 { get; set; }
        public string Defloc2 { get; set; }
        public string Defloc3 { get; set; }
        public string Defloc4 { get; set; }
        public string Defloc5 { get; set; }
        public string Defloc6 { get; set; }
        public string Defloc7 { get; set; }
        public string Defloc8 { get; set; }
        public string Defloc9 { get; set; }
        public string Defloc10 { get; set; }
        public string Defloc11 { get; set; }
        public string Defloc12 { get; set; }
        public string Defloc13 { get; set; }
        public string Defloc14 { get; set; }
        public byte Wippro0 { get; set; }
        public string Pck0 { get; set; }
        public decimal Pckcap0 { get; set; }
        public byte Stomgtcod0 { get; set; }
        public string Ptocod0 { get; set; }
        public byte Pckstkflg0 { get; set; }
        public byte Quaflg0 { get; set; }
        public string Qlycrd0 { get; set; }
        public string Quaacs0 { get; set; }
        public int Quafry0 { get; set; }
        public int Quanum0 { get; set; }
        public byte Smptyp0 { get; set; }
        public byte Smpmod0 { get; set; }
        public byte Genlevins0 { get; set; }
        public byte Nqa0 { get; set; }
        public int Quaadxuid0 { get; set; }
        public int Quanumuid0 { get; set; }
        public short Shllti0 { get; set; }
        public byte Shlltiuom0 { get; set; }
        public string Newltista0 { get; set; }
        public decimal Dlu0 { get; set; }
        public string Ltiqlycrd0 { get; set; }
        public string Ordwrh0 { get; set; }
        public string Matwrh0 { get; set; }
        public string Shiwrh0 { get; set; }
        public string Mfgwrh0 { get; set; }
        public string Trfwrh0 { get; set; }
        public string Scowrh0 { get; set; }
        public string Sccwrh0 { get; set; }
        public byte Pckflg0 { get; set; }
        public int Expnum0 { get; set; }
        public DateTime Credat0 { get; set; }
        public string Creusr0 { get; set; }
        public DateTime Upddat0 { get; set; }
        public string Updusr0 { get; set; }
        public string Stafed0 { get; set; }
        public string Frtcls0 { get; set; }
        public string Nmfc0 { get; set; }
        public DateTime Credattim0 { get; set; }
        public DateTime Upddattim0 { get; set; }
        public byte[] Auuid0 { get; set; }
        public decimal Rowid { get; set; }
    }
}
