using System;
using System.Collections.Generic;

namespace VipcoSageX3.Models.SageX3
{
    public partial class Itmmvt
    {
        public int Updtick0 { get; set; }
        public string Itmref0 { get; set; }
        public string Stofcy0 { get; set; }
        public decimal Physto0 { get; set; }
        public decimal Ctlsto0 { get; set; }
        public decimal Rejsto0 { get; set; }
        public decimal Plfphysto0 { get; set; }
        public decimal Plfctlsto0 { get; set; }
        public decimal Plfrejsto0 { get; set; }
        public decimal Bprphysto0 { get; set; }
        public decimal Bprctlsto0 { get; set; }
        public decimal Bprrejsto0 { get; set; }
        public decimal Scophysto0 { get; set; }
        public decimal Scoctlsto0 { get; set; }
        public decimal Scorejsto0 { get; set; }
        public decimal Phyall0 { get; set; }
        public decimal Ctlall0 { get; set; }
        public decimal Rejall0 { get; set; }
        public decimal Gloall0 { get; set; }
        public decimal Detsht0 { get; set; }
        public decimal Glosht0 { get; set; }
        public decimal Scophyall0 { get; set; }
        public decimal Scoctlall0 { get; set; }
        public decimal Scorejall0 { get; set; }
        public decimal Trfsto0 { get; set; }
        public decimal Trasto0 { get; set; }
        public decimal Traamt0 { get; set; }
        public decimal Ordsto0 { get; set; }
        public decimal Salsto0 { get; set; }
        public decimal Waisto0 { get; set; }
        public decimal Scclndsto0 { get; set; }
        public decimal Sccall0 { get; set; }
        public decimal Avc0 { get; set; }
        public decimal Avcbasqty0 { get; set; }
        public decimal Avcbasamt0 { get; set; }
        public DateTime Lasreodat0 { get; set; }
        public decimal Cunsto0 { get; set; }
        public DateTime Lascundat0 { get; set; }
        public int Cunnbr0 { get; set; }
        public int Cunnbrequ0 { get; set; }
        public short Cundim0 { get; set; }
        public DateTime Cundat0 { get; set; }
        public DateTime Cundat1 { get; set; }
        public DateTime Cundat2 { get; set; }
        public DateTime Cundat3 { get; set; }
        public DateTime Cundat4 { get; set; }
        public DateTime Cundat5 { get; set; }
        public DateTime Cundat6 { get; set; }
        public DateTime Cundat7 { get; set; }
        public DateTime Cundat8 { get; set; }
        public DateTime Cundat9 { get; set; }
        public DateTime Cundat10 { get; set; }
        public DateTime Cundat11 { get; set; }
        public decimal Cunqtyclc0 { get; set; }
        public decimal Cunqtyclc1 { get; set; }
        public decimal Cunqtyclc2 { get; set; }
        public decimal Cunqtyclc3 { get; set; }
        public decimal Cunqtyclc4 { get; set; }
        public decimal Cunqtyclc5 { get; set; }
        public decimal Cunqtyclc6 { get; set; }
        public decimal Cunqtyclc7 { get; set; }
        public decimal Cunqtyclc8 { get; set; }
        public decimal Cunqtyclc9 { get; set; }
        public decimal Cunqtyclc10 { get; set; }
        public decimal Cunqtyclc11 { get; set; }
        public decimal Cunqtynew0 { get; set; }
        public decimal Cunqtynew1 { get; set; }
        public decimal Cunqtynew2 { get; set; }
        public decimal Cunqtynew3 { get; set; }
        public decimal Cunqtynew4 { get; set; }
        public decimal Cunqtynew5 { get; set; }
        public decimal Cunqtynew6 { get; set; }
        public decimal Cunqtynew7 { get; set; }
        public decimal Cunqtynew8 { get; set; }
        public decimal Cunqtynew9 { get; set; }
        public decimal Cunqtynew10 { get; set; }
        public decimal Cunqtynew11 { get; set; }
        public int Cunrcpmvt0 { get; set; }
        public int Cunissmvt0 { get; set; }
        public DateTime Nexcundat0 { get; set; }
        public decimal Laspurpri0 { get; set; }
        public DateTime Laspurdat0 { get; set; }
        public decimal Lasrcppri0 { get; set; }
        public DateTime Lasrcpdat0 { get; set; }
        public byte Vcrtyp0 { get; set; }
        public string Vcrnum0 { get; set; }
        public int Vcrlin0 { get; set; }
        public DateTime Lasissdat0 { get; set; }
        public string Cfgvcrnum0 { get; set; }
        public string Lascunlis0 { get; set; }
        public decimal Amatavc0 { get; set; }
        public decimal Amatavc1 { get; set; }
        public decimal Amatavc2 { get; set; }
        public decimal Amatavc3 { get; set; }
        public decimal Amatavc4 { get; set; }
        public decimal Amatavc5 { get; set; }
        public decimal Amacavc0 { get; set; }
        public decimal Amacavc1 { get; set; }
        public decimal Amacavc2 { get; set; }
        public decimal Alabavc0 { get; set; }
        public decimal Alabavc1 { get; set; }
        public decimal Alabavc2 { get; set; }
        public decimal Ascoavc0 { get; set; }
        public decimal Ainvdtaavc0 { get; set; }
        public decimal Aovematavc0 { get; set; }
        public decimal Aovemacavc0 { get; set; }
        public decimal Aovelabavc0 { get; set; }
        public decimal Aovescoavc0 { get; set; }
        public decimal Amatcst0 { get; set; }
        public decimal Amatcst1 { get; set; }
        public decimal Amatcst2 { get; set; }
        public decimal Amatcst3 { get; set; }
        public decimal Amatcst4 { get; set; }
        public decimal Amatcst5 { get; set; }
        public decimal Amaccst0 { get; set; }
        public decimal Amaccst1 { get; set; }
        public decimal Amaccst2 { get; set; }
        public decimal Alabcst0 { get; set; }
        public decimal Alabcst1 { get; set; }
        public decimal Alabcst2 { get; set; }
        public decimal Ascocst0 { get; set; }
        public decimal Ainvdtacst0 { get; set; }
        public decimal Aovematcst0 { get; set; }
        public decimal Aovemaccst0 { get; set; }
        public decimal Aovelabcst0 { get; set; }
        public decimal Aovescocst0 { get; set; }
        public decimal Lmatcst0 { get; set; }
        public decimal Lmatcst1 { get; set; }
        public decimal Lmatcst2 { get; set; }
        public decimal Lmatcst3 { get; set; }
        public decimal Lmatcst4 { get; set; }
        public decimal Lmatcst5 { get; set; }
        public decimal Lmaccst0 { get; set; }
        public decimal Lmaccst1 { get; set; }
        public decimal Lmaccst2 { get; set; }
        public decimal Llabcst0 { get; set; }
        public decimal Llabcst1 { get; set; }
        public decimal Llabcst2 { get; set; }
        public decimal Lscocst0 { get; set; }
        public decimal Linvdtacst0 { get; set; }
        public decimal Lovematcst0 { get; set; }
        public decimal Lovemaccst0 { get; set; }
        public decimal Lovelabcst0 { get; set; }
        public decimal Lovescocst0 { get; set; }
        public int Expnum0 { get; set; }
        public DateTime Credat0 { get; set; }
        public string Creusr0 { get; set; }
        public DateTime Upddat0 { get; set; }
        public string Updusr0 { get; set; }
        public DateTime Credattim0 { get; set; }
        public DateTime Upddattim0 { get; set; }
        public byte[] Auuid0 { get; set; }
        public decimal Rowid { get; set; }
    }
}
