using System;
using System.Collections.Generic;

namespace VipcoSageX3.Models.SageX3
{
    public partial class Itmmaster
    {
        public int Updtick0 { get; set; }
        public string Itmref0 { get; set; }
        public string Cpy0 { get; set; }
        public string Tsicod0 { get; set; }
        public string Tsicod1 { get; set; }
        public string Tsicod2 { get; set; }
        public string Tsicod3 { get; set; }
        public string Tsicod4 { get; set; }
        public string Tclcod0 { get; set; }
        public string Seakey0 { get; set; }
        public string Die0 { get; set; }
        public string Die1 { get; set; }
        public string Die2 { get; set; }
        public string Die3 { get; set; }
        public string Die4 { get; set; }
        public string Die5 { get; set; }
        public string Die6 { get; set; }
        public string Die7 { get; set; }
        public string Die8 { get; set; }
        public string Die9 { get; set; }
        public string Die10 { get; set; }
        public string Die11 { get; set; }
        public string Die12 { get; set; }
        public string Die13 { get; set; }
        public string Die14 { get; set; }
        public string Die15 { get; set; }
        public string Die16 { get; set; }
        public string Die17 { get; set; }
        public string Die18 { get; set; }
        public string Die19 { get; set; }
        public string Cce0 { get; set; }
        public string Cce1 { get; set; }
        public string Cce2 { get; set; }
        public string Cce3 { get; set; }
        public string Cce4 { get; set; }
        public string Cce5 { get; set; }
        public string Cce6 { get; set; }
        public string Cce7 { get; set; }
        public string Cce8 { get; set; }
        public string Cce9 { get; set; }
        public string Cce10 { get; set; }
        public string Cce11 { get; set; }
        public string Cce12 { get; set; }
        public string Cce13 { get; set; }
        public string Cce14 { get; set; }
        public string Cce15 { get; set; }
        public string Cce16 { get; set; }
        public string Cce17 { get; set; }
        public string Cce18 { get; set; }
        public string Cce19 { get; set; }
        public string Acccod0 { get; set; }
        public string Itmdes10 { get; set; }
        public string Itmdes20 { get; set; }
        public string Itmdes30 { get; set; }
        public byte Stdflg0 { get; set; }
        public string Itmstd0 { get; set; }
        public string Eancod0 { get; set; }
        public byte Itmsta0 { get; set; }
        public decimal Defpot0 { get; set; }
        public decimal Defact0 { get; set; }
        public DateTime Lifstrdat0 { get; set; }
        public DateTime Lifenddat0 { get; set; }
        public string Stocrd0 { get; set; }
        public string Stu0 { get; set; }
        public string Puu0 { get; set; }
        public string Sau0 { get; set; }
        public string Ssu0 { get; set; }
        public string Eeu0 { get; set; }
        public decimal Puustucoe0 { get; set; }
        public byte Dacpuucoe0 { get; set; }
        public decimal Saustucoe0 { get; set; }
        public byte Dacsaucoe0 { get; set; }
        public decimal Ssustucoe0 { get; set; }
        public decimal Eeustucoe0 { get; set; }
        public string Weu0 { get; set; }
        public decimal Itmwei0 { get; set; }
        public string Vou0 { get; set; }
        public decimal Itmvou0 { get; set; }
        public string Pcu0 { get; set; }
        public string Pcu1 { get; set; }
        public string Pcu2 { get; set; }
        public string Pcu3 { get; set; }
        public decimal Pcustucoe0 { get; set; }
        public decimal Pcustucoe1 { get; set; }
        public decimal Pcustucoe2 { get; set; }
        public decimal Pcustucoe3 { get; set; }
        public byte Dacpcucoe0 { get; set; }
        public byte Dacpcucoe1 { get; set; }
        public byte Dacpcucoe2 { get; set; }
        public byte Dacpcucoe3 { get; set; }
        public byte Pcurul0 { get; set; }
        public byte Pcurul1 { get; set; }
        public byte Pcurul2 { get; set; }
        public byte Pcurul3 { get; set; }
        public string Lbefmt0 { get; set; }
        public string Lbefmt1 { get; set; }
        public string Lbefmt2 { get; set; }
        public string Lbefmt3 { get; set; }
        public byte Stomgtcod0 { get; set; }
        public byte Lotmgtcod0 { get; set; }
        public string Lotcou0 { get; set; }
        public string Sercou0 { get; set; }
        public byte Sermgtcod0 { get; set; }
        public byte Exymgtcod0 { get; set; }
        public string Exysta0 { get; set; }
        public short Shl0 { get; set; }
        public short Shllti0 { get; set; }
        public byte Negsto0 { get; set; }
        public string Cstgrp0 { get; set; }
        public byte Brdcod0 { get; set; }
        public string Plaacs0 { get; set; }
        public string Rplitm0 { get; set; }
        public byte Eecges0 { get; set; }
        public string Cusref0 { get; set; }
        public string Vacitm0 { get; set; }
        public string Vacitm1 { get; set; }
        public string Vacitm2 { get; set; }
        public byte Frthoruom0 { get; set; }
        public short Frthor0 { get; set; }
        public short Fimhor0 { get; set; }
        public byte Fimhoruom0 { get; set; }
        public string Buy0 { get; set; }
        public string Planner0 { get; set; }
        public short Ofs0 { get; set; }
        public decimal Purbaspri0 { get; set; }
        public decimal Cprcoe0 { get; set; }
        public decimal Cpramt0 { get; set; }
        public string Stcnum0 { get; set; }
        public decimal Minrmnprc0 { get; set; }
        public byte Rcpflg0 { get; set; }
        public byte Prqflg0 { get; set; }
        public string Purtex0 { get; set; }
        public string Mfgtex0 { get; set; }
        public string Itmexnflg0 { get; set; }
        public string Stataxflg0 { get; set; }
        public string Cfglin0 { get; set; }
        public decimal Cfgfldnum10 { get; set; }
        public decimal Cfgfldnum20 { get; set; }
        public decimal Cfgfldnum30 { get; set; }
        public decimal Cfgfldnum40 { get; set; }
        public decimal Cfgfldnum50 { get; set; }
        public decimal Cfgfldnum60 { get; set; }
        public string Cfgfldalp10 { get; set; }
        public string Cfgfldalp20 { get; set; }
        public string Cfgfldalp30 { get; set; }
        public string Cfgfldalp40 { get; set; }
        public string Cfgfldalp50 { get; set; }
        public string Cfgfldalp60 { get; set; }
        public string Cfgvcrnum0 { get; set; }
        public string Cfgbprnum0 { get; set; }
        public string Cfgbprref0 { get; set; }
        public string Cfgitmref0 { get; set; }
        public DateTime Cfgdeldat0 { get; set; }
        public byte Cremac0 { get; set; }
        public string Flycat0 { get; set; }
        public string Tplconlnd0 { get; set; }
        public string Tplcongua0 { get; set; }
        public string Tplconsrv0 { get; set; }
        public int Pitcdt0 { get; set; }
        public string Pitcdtuom0 { get; set; }
        public string Stulbefmt0 { get; set; }
        public short Altbomhdk0 { get; set; }
        public byte Hdkitmtyp0 { get; set; }
        public byte Stoissdef0 { get; set; }
        public string Dayuom0 { get; set; }
        public string Houuom0 { get; set; }
        public string Mntuom0 { get; set; }
        public decimal Dty0 { get; set; }
        public byte Trkcod0 { get; set; }
        public byte Trklev0 { get; set; }
        public byte Purflg0 { get; set; }
        public byte Mfgflg0 { get; set; }
        public byte Scpflg0 { get; set; }
        public byte Scsflg0 { get; set; }
        public byte Phaflg0 { get; set; }
        public byte Genflg0 { get; set; }
        public byte Tooflg0 { get; set; }
        public byte Dlvflg0 { get; set; }
        public byte Salflg0 { get; set; }
        public byte Intflg0 { get; set; }
        public byte Flgfas0 { get; set; }
        public string Newltista0 { get; set; }
        public decimal Dlu0 { get; set; }
        public byte Shluom0 { get; set; }
        public byte Shlltiuom0 { get; set; }
        public int Expnum0 { get; set; }
        public DateTime Credat0 { get; set; }
        public string Creusr0 { get; set; }
        public DateTime Upddat0 { get; set; }
        public string Updusr0 { get; set; }
        public string Stafed0 { get; set; }
        public string Plmitmref0 { get; set; }
        public string Plmatturl0 { get; set; }
        public string Plmhisurl0 { get; set; }
        public string Pcccod0 { get; set; }
        public string Mattol0 { get; set; }
        public string Sstcod0 { get; set; }
        public string Alg0 { get; set; }
        public DateTime Algdat0 { get; set; }
        public short Algbom0 { get; set; }
        public DateTime Credattim0 { get; set; }
        public DateTime Upddattim0 { get; set; }
        public byte[] Auuid0 { get; set; }
        public byte Itmsfttyp0 { get; set; }
        public byte Eccflg0 { get; set; }
        public byte Eccsto0 { get; set; }
        public string Eccmin0 { get; set; }
        public string Eccmaj0 { get; set; }
        public short Eccbomalt20 { get; set; }
        public short Eccbomalt21 { get; set; }
        public short Eccbomalt30 { get; set; }
        public short Eccbomalt31 { get; set; }
        public byte Loaeccflg0 { get; set; }
        public short Invprodtyp0 { get; set; }
        public byte Eccrouflg0 { get; set; }
        public short Eccroualt0 { get; set; }
        public short Eccroualt1 { get; set; }
        public decimal Rowid { get; set; }
    }
}
