using System;
using System.Collections.Generic;

namespace VipcoSageX3.Models.SageX3
{
    public partial class Paymenth
    {
        public int Updtick0 { get; set; }
        public string Num0 { get; set; }
        public byte Frmflg0 { get; set; }
        public string Frmnum0 { get; set; }
        public short Frmlin0 { get; set; }
        public string Frmref0 { get; set; }
        public string Bpr0 { get; set; }
        public string Bprsac0 { get; set; }
        public string Coa0 { get; set; }
        public string Acc0 { get; set; }
        public string Paytyp0 { get; set; }
        public string Pam0 { get; set; }
        public string Cpy0 { get; set; }
        public string Fcy0 { get; set; }
        public string Ban0 { get; set; }
        public string Des0 { get; set; }
        public byte Sns0 { get; set; }
        public string Cur0 { get; set; }
        public decimal Amtcur0 { get; set; }
        public decimal Amtban0 { get; set; }
        public decimal Banpaytpy0 { get; set; }
        public decimal Amtnytbil0 { get; set; }
        public byte Bprtyp0 { get; set; }
        public decimal Pabamtprt0 { get; set; }
        public byte Pabflg0 { get; set; }
        public string Pabren0 { get; set; }
        public byte Sta0 { get; set; }
        public byte Staflg0 { get; set; }
        public byte Staflg1 { get; set; }
        public byte Staflg2 { get; set; }
        public byte Staflg3 { get; set; }
        public byte Staflg4 { get; set; }
        public byte Staflg5 { get; set; }
        public byte Staflg6 { get; set; }
        public byte Staflg7 { get; set; }
        public byte Staflg8 { get; set; }
        public byte Staflg9 { get; set; }
        public byte Staflg10 { get; set; }
        public int Accnumtre0 { get; set; }
        public int Accnumtre1 { get; set; }
        public int Accnumtre2 { get; set; }
        public int Accnumtre3 { get; set; }
        public int Accnumtre4 { get; set; }
        public int Accnumtre5 { get; set; }
        public int Accnumtre6 { get; set; }
        public int Accnumtre7 { get; set; }
        public int Accnumtre8 { get; set; }
        public int Accnumtre9 { get; set; }
        public int Accnumtre10 { get; set; }
        public string Numord0 { get; set; }
        public string Paynumend0 { get; set; }
        public string Senbpr0 { get; set; }
        public string Sencrn0 { get; set; }
        public string Senori0 { get; set; }
        public short Flgend0 { get; set; }
        public string Rennotpay0 { get; set; }
        public DateTime Accdat0 { get; set; }
        public string Ref0 { get; set; }
        public DateTime Oridat0 { get; set; }
        public DateTime Duddat0 { get; set; }
        public DateTime Bandat0 { get; set; }
        public DateTime Valdat0 { get; set; }
        public DateTime Bildat0 { get; set; }
        public string Bidcry0 { get; set; }
        public string Bid0 { get; set; }
        public string Pab10 { get; set; }
        public string Pab20 { get; set; }
        public string Pab30 { get; set; }
        public string Pab40 { get; set; }
        public string Biccod0 { get; set; }
        public string Midpab10 { get; set; }
        public string Midpab20 { get; set; }
        public string Midpab30 { get; set; }
        public string Midpab40 { get; set; }
        public string Midbiccod0 { get; set; }
        public string Midcry0 { get; set; }
        public string Bprref0 { get; set; }
        public byte Chqtyp0 { get; set; }
        public string Chqban0 { get; set; }
        public string Chqnum0 { get; set; }
        public string Crdnum0 { get; set; }
        public DateTime Crdexydat0 { get; set; }
        public string Crdtyp0 { get; set; }
        public string Crdauz0 { get; set; }
        public byte Frmtyp0 { get; set; }
        public byte Purtyp0 { get; set; }
        public string Sup10 { get; set; }
        public string Sup20 { get; set; }
        public string Sup30 { get; set; }
        public string Bdfmvtcod0 { get; set; }
        public string Bdfpaycod0 { get; set; }
        public string Bdfecocod0 { get; set; }
        public short Pst0 { get; set; }
        public DateTime Credat0 { get; set; }
        public DateTime Upddat0 { get; set; }
        public string Creusr0 { get; set; }
        public string Updusr0 { get; set; }
        public string Frmusr0 { get; set; }
        public DateTime Frmdat0 { get; set; }
        public string Frmfcy0 { get; set; }
        public short Fiy0 { get; set; }
        public short Per0 { get; set; }
        public int Expnum0 { get; set; }
        public int Edtnum0 { get; set; }
        public DateTime Tfbdat0 { get; set; }
        public string Tfbfil0 { get; set; }
        public string Paylot0 { get; set; }
        public short Paylotlig0 { get; set; }
        public string Bilvcr0 { get; set; }
        public string Bpainv0 { get; set; }
        public string Bpanam0 { get; set; }
        public string Bpaaddlig0 { get; set; }
        public string Bpaaddlig1 { get; set; }
        public string Bpaaddlig2 { get; set; }
        public string Poscod0 { get; set; }
        public string Cty0 { get; set; }
        public string Sat0 { get; set; }
        public string Cry0 { get; set; }
        public string Crynam0 { get; set; }
        public string Acs0 { get; set; }
        public string Epanatpay0 { get; set; }
        public string Eparenpay0 { get; set; }
        public DateTime Credattim0 { get; set; }
        public DateTime Upddattim0 { get; set; }
        public byte[] Auuid0 { get; set; }
        public string Umrnum0 { get; set; }
        public string Umrseq0 { get; set; }
        public short Vatsta0 { get; set; }
        public string Cashvatnum0 { get; set; }
        public DateTime Comdat0 { get; set; }
        public short Cshvatrgm0 { get; set; }
        public short Swisup10 { get; set; }
        public short Swisup20 { get; set; }
        public short Swisup30 { get; set; }
        public string Swiipi0 { get; set; }
        public string Bsitrs0 { get; set; }
        public decimal Ztaxbase0 { get; set; }
        public decimal Rowid { get; set; }
    }
}
