using System;
using System.Collections.Generic;

namespace VipcoSageX3.Models.SageX3
{
    public partial class Porderq
    {
        public int Updtick0 { get; set; }
        public string Pohnum0 { get; set; }
        public int Poplin0 { get; set; }
        public int Poqseq0 { get; set; }
        public string Poqlnk0 { get; set; }
        public string Cpy0 { get; set; }
        public string Pohfcy0 { get; set; }
        public byte Pohtyp0 { get; set; }
        public DateTime Orddat0 { get; set; }
        public string Bpsnum0 { get; set; }
        public string Bpsinv0 { get; set; }
        public string Bpainv0 { get; set; }
        public short Linrevnum0 { get; set; }
        public string Itmref0 { get; set; }
        public string Itmrefbps0 { get; set; }
        public string Puu0 { get; set; }
        public string Stu0 { get; set; }
        public string Uom0 { get; set; }
        public byte Uomflg0 { get; set; }
        public decimal Uompuucoe0 { get; set; }
        public decimal Likqtycoe0 { get; set; }
        public decimal Qtyuom0 { get; set; }
        public decimal Qtypuu0 { get; set; }
        public decimal Qtystu0 { get; set; }
        public decimal Qtyweu0 { get; set; }
        public string Linweu0 { get; set; }
        public decimal Qtyvou0 { get; set; }
        public string Linvou0 { get; set; }
        public decimal Retqtypuu0 { get; set; }
        public decimal Retqtystu0 { get; set; }
        public decimal Rcpqtypuu0 { get; set; }
        public decimal Rcpqtystu0 { get; set; }
        public decimal Invqtypuu0 { get; set; }
        public decimal Invqtystu0 { get; set; }
        public DateTime Retrcpdat0 { get; set; }
        public DateTime Extrcpdat0 { get; set; }
        public string Linstofcy0 { get; set; }
        public string Prhfcy0 { get; set; }
        public string Fcyadd0 { get; set; }
        public decimal Ofs0 { get; set; }
        public string Useplc0 { get; set; }
        public string Scoadd0 { get; set; }
        public byte Wiptyp0 { get; set; }
        public byte Wipsta0 { get; set; }
        public string Wipnum0 { get; set; }
        public byte Linpurtyp0 { get; set; }
        public DateTime Lasrcpdat0 { get; set; }
        public DateTime Lasinvdat0 { get; set; }
        public short Invrcpnbr0 { get; set; }
        public short Linrcpnbr0 { get; set; }
        public short Lininvnbr0 { get; set; }
        public string Lintex0 { get; set; }
        public byte Rcpcleflg0 { get; set; }
        public byte Lincleflg0 { get; set; }
        public byte Lininvflg0 { get; set; }
        public byte Linprnflg0 { get; set; }
        public byte Cmmtax0 { get; set; }
        public string Cmmnum0 { get; set; }
        public short Cmmflg0 { get; set; }
        public byte Fbuflg0 { get; set; }
        public byte Ori0 { get; set; }
        public DateTime Linocndat0 { get; set; }
        public string Linocnnum0 { get; set; }
        public short Linocnflg0 { get; set; }
        public string Netcur0 { get; set; }
        public decimal Cprcoe0 { get; set; }
        public decimal Cpramt0 { get; set; }
        public string Stcnum0 { get; set; }
        public decimal Cstpur0 { get; set; }
        public decimal Cpr0 { get; set; }
        public string Cprcur0 { get; set; }
        public decimal Cprpri0 { get; set; }
        public decimal Fcscstpur0 { get; set; }
        public decimal Fcscpr0 { get; set; }
        public decimal Linamt0 { get; set; }
        public decimal Linamtcpr0 { get; set; }
        public decimal Lincstpur0 { get; set; }
        public decimal Reacstpur0 { get; set; }
        public decimal Linati0 { get; set; }
        public decimal Linatiamt0 { get; set; }
        public decimal Discrgamt10 { get; set; }
        public decimal Discrgamt20 { get; set; }
        public decimal Discrgamt30 { get; set; }
        public decimal Discrgamt40 { get; set; }
        public decimal Discrgamt50 { get; set; }
        public decimal Discrgamt60 { get; set; }
        public decimal Discrgamt70 { get; set; }
        public decimal Discrgamt80 { get; set; }
        public decimal Discrgamt90 { get; set; }
        public decimal Clcamt10 { get; set; }
        public decimal Clcamt20 { get; set; }
        public decimal Clcamt30 { get; set; }
        public decimal Clcamt40 { get; set; }
        public decimal Clcamt50 { get; set; }
        public decimal Clcamt60 { get; set; }
        public decimal Clcamt70 { get; set; }
        public decimal Disbaslin10 { get; set; }
        public decimal Bastaxlin10 { get; set; }
        public decimal Amttaxlin10 { get; set; }
        public decimal Amttaxlin20 { get; set; }
        public decimal Amttaxlin30 { get; set; }
        public decimal Amttaxrcp0 { get; set; }
        public decimal Amttaxiss0 { get; set; }
        public decimal Amttaxoth10 { get; set; }
        public decimal Amttaxoth20 { get; set; }
        public decimal Dedtaxlin10 { get; set; }
        public decimal Dedtaxlin20 { get; set; }
        public decimal Dedtaxlin30 { get; set; }
        public decimal Dedtaxrcp0 { get; set; }
        public decimal Dedtaxiss0 { get; set; }
        public decimal Dedtaxoth10 { get; set; }
        public decimal Dedtaxoth20 { get; set; }
        public string Pqhnum0 { get; set; }
        public int Ppdlin0 { get; set; }
        public string Sohnum0 { get; set; }
        public int Soplin0 { get; set; }
        public int Soqseq0 { get; set; }
        public string Sdhnum0 { get; set; }
        public int Sddlin0 { get; set; }
        public byte Cad0 { get; set; }
        public short Yea0 { get; set; }
        public short Mon0 { get; set; }
        public short Wee0 { get; set; }
        public byte Linsta0 { get; set; }
        public byte Lintyp0 { get; set; }
        public DateTime Demrcpdat0 { get; set; }
        public short Demrcphou0 { get; set; }
        public DateTime Demenddat0 { get; set; }
        public short Demendhou0 { get; set; }
        public string Itmrefori0 { get; set; }
        public byte Vcrtypori0 { get; set; }
        public string Vcrnumori0 { get; set; }
        public int Vcrlinori0 { get; set; }
        public int Vcrseqori0 { get; set; }
        public string Pthnum0 { get; set; }
        public int Ptdlin0 { get; set; }
        public int Ocnlin0 { get; set; }
        public int Ocnseq0 { get; set; }
        public int Expnum0 { get; set; }
        public string Creusr0 { get; set; }
        public DateTime Credat0 { get; set; }
        public string Updusr0 { get; set; }
        public DateTime Upddat0 { get; set; }
        public DateTime Credattim0 { get; set; }
        public DateTime Upddattim0 { get; set; }
        public byte[] Auuid0 { get; set; }
        public string Eccvalmaj0 { get; set; }
        public string Eccvalmin0 { get; set; }
        public decimal Shiqtystu0 { get; set; }
        public decimal Shiqtypuu0 { get; set; }
        public decimal Zpo220 { get; set; }
        public decimal Rowid { get; set; }
    }
}
