using System;
using System.Collections.Generic;

namespace VipcoSageX3.Models.SageX3
{
    public partial class Preceipt
    {
        public int Updtick0 { get; set; }
        public string Pthnum0 { get; set; }
        public string Cpy0 { get; set; }
        public string Prhfcy0 { get; set; }
        public byte Purtyp0 { get; set; }
        public string Bpsnde0 { get; set; }
        public DateTime Ndedat0 { get; set; }
        public DateTime Rcpdat0 { get; set; }
        public string Bpsnum0 { get; set; }
        public string Bpaadd0 { get; set; }
        public string Bpoadd0 { get; set; }
        public string Bponam0 { get; set; }
        public string Bponam1 { get; set; }
        public string Bpoaddlig0 { get; set; }
        public string Bpoaddlig1 { get; set; }
        public string Bpoaddlig2 { get; set; }
        public string Bpoposcod0 { get; set; }
        public string Bpocty0 { get; set; }
        public string Bposat0 { get; set; }
        public string Bpocry0 { get; set; }
        public string Bpocrynam0 { get; set; }
        public string Bpsinv0 { get; set; }
        public string Bpainv0 { get; set; }
        public string Bprpay0 { get; set; }
        public string Bpapay0 { get; set; }
        public string Bptnum0 { get; set; }
        public string Ffwnum0 { get; set; }
        public string Ffwadd0 { get; set; }
        public string Tsscod0 { get; set; }
        public string Tsscod1 { get; set; }
        public string Tsscod2 { get; set; }
        public string Tsscod3 { get; set; }
        public string Tsscod4 { get; set; }
        public string Cur0 { get; set; }
        public byte Chgtyp0 { get; set; }
        public decimal Chgcoe0 { get; set; }
        public string Vacbpr0 { get; set; }
        public short Vactyp0 { get; set; }
        public string Dep0 { get; set; }
        public string Mdl0 { get; set; }
        public string Eecnat0 { get; set; }
        public string Eecsch0 { get; set; }
        public byte Eectrn0 { get; set; }
        public string Eecict0 { get; set; }
        public string Ictcty0 { get; set; }
        public byte Eecloc0 { get; set; }
        public string Eecnum0 { get; set; }
        public short Eecnumdeb0 { get; set; }
        public string Pjth0 { get; set; }
        public string Gpgcod0 { get; set; }
        public string Weu0 { get; set; }
        public string Vou0 { get; set; }
        public decimal Totgrowei0 { get; set; }
        public decimal Totnetwei0 { get; set; }
        public decimal Totvol0 { get; set; }
        public short Linnbr0 { get; set; }
        public short Invlinnbr0 { get; set; }
        public short Invlinctr0 { get; set; }
        public short Pstlinnbr0 { get; set; }
        public byte Prnflg0 { get; set; }
        public byte Invflg0 { get; set; }
        public byte Pstflg0 { get; set; }
        public DateTime Pstdat0 { get; set; }
        public byte Betfcy0 { get; set; }
        public byte Betcpy0 { get; set; }
        public string Tex10 { get; set; }
        public string Tex20 { get; set; }
        public string Trscod0 { get; set; }
        public string Entcod0 { get; set; }
        public string Cai0 { get; set; }
        public DateTime Datvlycai0 { get; set; }
        public string Typvcr0 { get; set; }
        public string Clsvcr0 { get; set; }
        public string Scuvcr0 { get; set; }
        public string Seqvcr0 { get; set; }
        public string Die0 { get; set; }
        public string Die1 { get; set; }
        public string Die2 { get; set; }
        public string Die3 { get; set; }
        public string Die4 { get; set; }
        public string Die5 { get; set; }
        public string Die6 { get; set; }
        public string Die7 { get; set; }
        public string Die8 { get; set; }
        public string Die9 { get; set; }
        public string Die10 { get; set; }
        public string Die11 { get; set; }
        public string Die12 { get; set; }
        public string Die13 { get; set; }
        public string Die14 { get; set; }
        public string Die15 { get; set; }
        public string Die16 { get; set; }
        public string Die17 { get; set; }
        public string Die18 { get; set; }
        public string Die19 { get; set; }
        public string Cce0 { get; set; }
        public string Cce1 { get; set; }
        public string Cce2 { get; set; }
        public string Cce3 { get; set; }
        public string Cce4 { get; set; }
        public string Cce5 { get; set; }
        public string Cce6 { get; set; }
        public string Cce7 { get; set; }
        public string Cce8 { get; set; }
        public string Cce9 { get; set; }
        public string Cce10 { get; set; }
        public string Cce11 { get; set; }
        public string Cce12 { get; set; }
        public string Cce13 { get; set; }
        public string Cce14 { get; set; }
        public string Cce15 { get; set; }
        public string Cce16 { get; set; }
        public string Cce17 { get; set; }
        public string Cce18 { get; set; }
        public string Cce19 { get; set; }
        public string Dspweu0 { get; set; }
        public string Dspvou0 { get; set; }
        public decimal Totlinamt0 { get; set; }
        public decimal Totlinqty0 { get; set; }
        public decimal Totlinweu0 { get; set; }
        public decimal Totlinvou0 { get; set; }
        public decimal Totamtnot0 { get; set; }
        public decimal Totamtnotl0 { get; set; }
        public decimal Tottaxamt0 { get; set; }
        public decimal Totamtati0 { get; set; }
        public decimal Totamtatil0 { get; set; }
        public short Invdtalin10 { get; set; }
        public short Invdtalin11 { get; set; }
        public short Invdtalin12 { get; set; }
        public short Invdtalin13 { get; set; }
        public short Invdtalin14 { get; set; }
        public short Invdtalin15 { get; set; }
        public short Invdtalin16 { get; set; }
        public short Invdtalin17 { get; set; }
        public short Invdtalin18 { get; set; }
        public string Invdtavat10 { get; set; }
        public string Invdtavat11 { get; set; }
        public string Invdtavat12 { get; set; }
        public string Invdtavat13 { get; set; }
        public string Invdtavat14 { get; set; }
        public string Invdtavat15 { get; set; }
        public string Invdtavat16 { get; set; }
        public string Invdtavat17 { get; set; }
        public string Invdtavat18 { get; set; }
        public short Invdtalin20 { get; set; }
        public short Invdtalin21 { get; set; }
        public short Invdtalin22 { get; set; }
        public short Invdtalin23 { get; set; }
        public short Invdtalin24 { get; set; }
        public short Invdtalin25 { get; set; }
        public short Invdtalin26 { get; set; }
        public short Invdtalin27 { get; set; }
        public short Invdtalin28 { get; set; }
        public string Invdtavat20 { get; set; }
        public string Invdtavat21 { get; set; }
        public string Invdtavat22 { get; set; }
        public string Invdtavat23 { get; set; }
        public string Invdtavat24 { get; set; }
        public string Invdtavat25 { get; set; }
        public string Invdtavat26 { get; set; }
        public string Invdtavat27 { get; set; }
        public string Invdtavat28 { get; set; }
        public string Wrhe0 { get; set; }
        public int Expnum0 { get; set; }
        public string Creusr0 { get; set; }
        public DateTime Credat0 { get; set; }
        public string Updusr0 { get; set; }
        public DateTime Upddat0 { get; set; }
        public DateTime Credattim0 { get; set; }
        public DateTime Upddattim0 { get; set; }
        public byte[] Auuid0 { get; set; }
        public string Licplate0 { get; set; }
        public string Trllicplate0 { get; set; }
        public DateTime Dpedat0 { get; set; }
        public DateTime Arvdat0 { get; set; }
        public string Etd0 { get; set; }
        public string Eta0 { get; set; }
        public byte Zprc010 { get; set; }
        public string Zprc020 { get; set; }
        public string Zprc030 { get; set; }
        public string Zprc040 { get; set; }
        public byte Zprc050 { get; set; }
        public byte Zprc060 { get; set; }
        public string Zprc070 { get; set; }
        public byte Zprc080 { get; set; }
        public byte Zprc090 { get; set; }
        public string Zprc100 { get; set; }
        public string Zprc110 { get; set; }
        public string Zprc120 { get; set; }
        public byte Zprc130 { get; set; }
        public string Zprc140 { get; set; }
        public string Zpo040 { get; set; }
        public string Zprc180 { get; set; }
        public string Zprc150 { get; set; }
        public decimal Rowid { get; set; }
    }
}
