using System;
using System.Collections.Generic;

namespace VipcoSageX3.Models.SageX3
{
    public partial class Prequis
    {
        public int Updtick0 { get; set; }
        public string Pshnum0 { get; set; }
        public string Cpy0 { get; set; }
        public string Pshfcy0 { get; set; }
        public DateTime Prqdat0 { get; set; }
        public string Die0 { get; set; }
        public string Die1 { get; set; }
        public string Die2 { get; set; }
        public string Die3 { get; set; }
        public string Die4 { get; set; }
        public string Die5 { get; set; }
        public string Die6 { get; set; }
        public string Die7 { get; set; }
        public string Die8 { get; set; }
        public string Die9 { get; set; }
        public string Die10 { get; set; }
        public string Die11 { get; set; }
        public string Die12 { get; set; }
        public string Die13 { get; set; }
        public string Die14 { get; set; }
        public string Die15 { get; set; }
        public string Die16 { get; set; }
        public string Die17 { get; set; }
        public string Die18 { get; set; }
        public string Die19 { get; set; }
        public string Cce0 { get; set; }
        public string Cce1 { get; set; }
        public string Cce2 { get; set; }
        public string Cce3 { get; set; }
        public string Cce4 { get; set; }
        public string Cce5 { get; set; }
        public string Cce6 { get; set; }
        public string Cce7 { get; set; }
        public string Cce8 { get; set; }
        public string Cce9 { get; set; }
        public string Cce10 { get; set; }
        public string Cce11 { get; set; }
        public string Cce12 { get; set; }
        public string Cce13 { get; set; }
        public string Cce14 { get; set; }
        public string Cce15 { get; set; }
        public string Cce16 { get; set; }
        public string Cce17 { get; set; }
        public string Cce18 { get; set; }
        public string Cce19 { get; set; }
        public string Pjth0 { get; set; }
        public short Linnbr0 { get; set; }
        public short Fbulinnbr0 { get; set; }
        public short Applinnbr0 { get; set; }
        public short Ordlinnbr0 { get; set; }
        public short Clelinnbr0 { get; set; }
        public byte Appflg0 { get; set; }
        public byte Ordflg0 { get; set; }
        public byte Cleflg0 { get; set; }
        public byte Prnflg0 { get; set; }
        public string Tex10 { get; set; }
        public string Tex20 { get; set; }
        public string Requsr0 { get; set; }
        public decimal Totprq0 { get; set; }
        public string Pshnummms0 { get; set; }
        public string Mmsurl0 { get; set; }
        public int Expnum0 { get; set; }
        public string Creusr0 { get; set; }
        public DateTime Credat0 { get; set; }
        public string Updusr0 { get; set; }
        public DateTime Upddat0 { get; set; }
        public DateTime Credattim0 { get; set; }
        public DateTime Upddattim0 { get; set; }
        public byte[] Auuid0 { get; set; }
        public byte Atecori0 { get; set; }
        public string Zpr010 { get; set; }
        public string Zpr020 { get; set; }
        public string Zpr030 { get; set; }
        public string Zpr040 { get; set; }
        public string Zpr050 { get; set; }
        public string Zpr060 { get; set; }
        public string Zpr070 { get; set; }
        public string Zpr080 { get; set; }
        public string Zpr090 { get; set; }
        public byte Zpr100 { get; set; }
        public string Zpr110 { get; set; }
        public DateTime Zpr120 { get; set; }
        public byte Zpr130 { get; set; }
        public byte Zpr140 { get; set; }
        public byte Zpr150 { get; set; }
        public byte Zpr160 { get; set; }
        public byte Zpr170 { get; set; }
        public byte Zpr180 { get; set; }
        public string Zpr190 { get; set; }
        public string Zpr200 { get; set; }
        public string Zpr210 { get; set; }
        public string Zpr220 { get; set; }
        public string Zpr230 { get; set; }
        public string Zpr240 { get; set; }
        public string Zpr250 { get; set; }
        public string Zpr260 { get; set; }
        public string Zpr270 { get; set; }
        public string Zpr280 { get; set; }
        public string Zpr290 { get; set; }
        public byte Zpr300 { get; set; }
        public decimal Rowid { get; set; }
    }
}
