using System;
using System.Collections.Generic;

namespace VipcoSageX3.Models.SageX3
{
    public partial class Prequisd
    {
        public int Updtick0 { get; set; }
        public string Pshnum0 { get; set; }
        public int Psdlin0 { get; set; }
        public string Cpy0 { get; set; }
        public string Pshfcy0 { get; set; }
        public string Itmref0 { get; set; }
        public string Itmdes10 { get; set; }
        public string Itmdes0 { get; set; }
        public string Bpsnum0 { get; set; }
        public decimal Qtypuu0 { get; set; }
        public decimal Qtystu0 { get; set; }
        public decimal Ordqtypuu0 { get; set; }
        public decimal Ordqtystu0 { get; set; }
        public string Puu0 { get; set; }
        public string Stu0 { get; set; }
        public string Vacbpr0 { get; set; }
        public short Vactyp0 { get; set; }
        public string Cur0 { get; set; }
        public byte Chgtyp0 { get; set; }
        public decimal Chgcoe0 { get; set; }
        public decimal Gropri0 { get; set; }
        public decimal Netpri0 { get; set; }
        public decimal Discrgval10 { get; set; }
        public decimal Discrgval20 { get; set; }
        public decimal Discrgval30 { get; set; }
        public decimal Discrgval40 { get; set; }
        public decimal Discrgval50 { get; set; }
        public decimal Discrgval60 { get; set; }
        public decimal Discrgval70 { get; set; }
        public decimal Discrgval80 { get; set; }
        public decimal Discrgval90 { get; set; }
        public short Priren0 { get; set; }
        public short Discrgren10 { get; set; }
        public short Discrgren20 { get; set; }
        public short Discrgren30 { get; set; }
        public short Discrgren40 { get; set; }
        public short Discrgren50 { get; set; }
        public short Discrgren60 { get; set; }
        public short Discrgren70 { get; set; }
        public short Discrgren80 { get; set; }
        public short Discrgren90 { get; set; }
        public decimal Linamt0 { get; set; }
        public DateTime Extorddat0 { get; set; }
        public DateTime Extrcpdat0 { get; set; }
        public string Linbuy0 { get; set; }
        public byte Linpurtyp0 { get; set; }
        public string Pjt0 { get; set; }
        public string Prhfcy0 { get; set; }
        public string Vat0 { get; set; }
        public string Vat1 { get; set; }
        public string Vat2 { get; set; }
        public string Taxrcp0 { get; set; }
        public string Taxiss0 { get; set; }
        public string Taxoth10 { get; set; }
        public string Taxoth20 { get; set; }
        public decimal Clcamt10 { get; set; }
        public decimal Clcamt20 { get; set; }
        public decimal Clcamt30 { get; set; }
        public decimal Clcamt40 { get; set; }
        public decimal Clcamt50 { get; set; }
        public decimal Clcamt60 { get; set; }
        public decimal Clcamt70 { get; set; }
        public decimal Linatiamt0 { get; set; }
        public decimal Bastaxlin10 { get; set; }
        public decimal Amttaxlin10 { get; set; }
        public decimal Amttaxlin20 { get; set; }
        public decimal Amttaxlin30 { get; set; }
        public decimal Amttaxrcp0 { get; set; }
        public decimal Amttaxiss0 { get; set; }
        public decimal Amttaxoth10 { get; set; }
        public decimal Amttaxoth20 { get; set; }
        public decimal Dedtaxlin10 { get; set; }
        public decimal Dedtaxlin20 { get; set; }
        public decimal Dedtaxlin30 { get; set; }
        public decimal Dedtaxrcp0 { get; set; }
        public decimal Dedtaxiss0 { get; set; }
        public decimal Dedtaxoth10 { get; set; }
        public decimal Dedtaxoth20 { get; set; }
        public string Lintex0 { get; set; }
        public byte Lincleflg0 { get; set; }
        public byte Linordflg0 { get; set; }
        public byte Linappflg0 { get; set; }
        public byte Cmmprptax0 { get; set; }
        public string Cmmprpnum0 { get; set; }
        public short Cmmprpflg0 { get; set; }
        public byte Fbuflg0 { get; set; }
        public byte Ori0 { get; set; }
        public string Pqhnum0 { get; set; }
        public int Ppdlin0 { get; set; }
        public string Wipnum0 { get; set; }
        public int Nbaof0 { get; set; }
        public string Psdnummms0 { get; set; }
        public string Creusr0 { get; set; }
        public DateTime Credat0 { get; set; }
        public string Updusr0 { get; set; }
        public DateTime Upddat0 { get; set; }
        public DateTime Credattim0 { get; set; }
        public DateTime Upddattim0 { get; set; }
        public byte[] Auuid0 { get; set; }
        public byte Atecori0 { get; set; }
        public string Eccvalmaj0 { get; set; }
        public string Eccvalmin0 { get; set; }
        public decimal Rowid { get; set; }
    }
}
