using System;
using System.Collections.Generic;

namespace VipcoSageX3.Models.SageX3
{
    public partial class Preturnd
    {
        public int Updtick0 { get; set; }
        public string Pnhnum0 { get; set; }
        public int Pndlin0 { get; set; }
        public string Cpy0 { get; set; }
        public string Pnhfcy0 { get; set; }
        public DateTime Rtndat0 { get; set; }
        public string Pohfcy0 { get; set; }
        public string Pohnum0 { get; set; }
        public int Poplin0 { get; set; }
        public int Poqseq0 { get; set; }
        public byte Pohtyp0 { get; set; }
        public string Pthnum0 { get; set; }
        public int Ptdlin0 { get; set; }
        public string Bpsnde0 { get; set; }
        public string Bpsnum0 { get; set; }
        public string Bpsinv0 { get; set; }
        public string Bpainv0 { get; set; }
        public string Itmref0 { get; set; }
        public string Itmdes10 { get; set; }
        public string Itmdes0 { get; set; }
        public decimal Qtyuom0 { get; set; }
        public decimal Qtypuu0 { get; set; }
        public decimal Qtystu0 { get; set; }
        public decimal Invqtypuu0 { get; set; }
        public decimal Invqtystu0 { get; set; }
        public decimal Srdqtystu0 { get; set; }
        public byte Uomflg0 { get; set; }
        public decimal Uompuucoe0 { get; set; }
        public decimal Uomstucoe0 { get; set; }
        public string Uom0 { get; set; }
        public string Puu0 { get; set; }
        public string Stu0 { get; set; }
        public string Weu0 { get; set; }
        public string Cprcur0 { get; set; }
        public string Netcur0 { get; set; }
        public decimal Untwei0 { get; set; }
        public string Rtnren0 { get; set; }
        public string Rtndes0 { get; set; }
        public decimal Gropri0 { get; set; }
        public short Priren0 { get; set; }
        public decimal Discrgval10 { get; set; }
        public decimal Discrgval20 { get; set; }
        public decimal Discrgval30 { get; set; }
        public decimal Discrgval40 { get; set; }
        public decimal Discrgval50 { get; set; }
        public decimal Discrgval60 { get; set; }
        public decimal Discrgval70 { get; set; }
        public decimal Discrgval80 { get; set; }
        public decimal Discrgval90 { get; set; }
        public short Discrgren10 { get; set; }
        public short Discrgren20 { get; set; }
        public short Discrgren30 { get; set; }
        public short Discrgren40 { get; set; }
        public short Discrgren50 { get; set; }
        public short Discrgren60 { get; set; }
        public short Discrgren70 { get; set; }
        public short Discrgren80 { get; set; }
        public short Discrgren90 { get; set; }
        public decimal Netpri0 { get; set; }
        public decimal Netpripuu0 { get; set; }
        public decimal Linamt0 { get; set; }
        public decimal Linatiamt0 { get; set; }
        public decimal Clcamt10 { get; set; }
        public decimal Clcamt20 { get; set; }
        public decimal Clcamt30 { get; set; }
        public decimal Clcamt40 { get; set; }
        public decimal Clcamt50 { get; set; }
        public decimal Clcamt60 { get; set; }
        public decimal Clcamt70 { get; set; }
        public decimal Bastaxlin10 { get; set; }
        public decimal Amttaxlin10 { get; set; }
        public decimal Amttaxlin20 { get; set; }
        public decimal Amttaxlin30 { get; set; }
        public decimal Amttaxrcp0 { get; set; }
        public decimal Amttaxiss0 { get; set; }
        public decimal Amttaxoth10 { get; set; }
        public decimal Amttaxoth20 { get; set; }
        public decimal Dedtaxlin10 { get; set; }
        public decimal Dedtaxlin20 { get; set; }
        public decimal Dedtaxlin30 { get; set; }
        public decimal Dedtaxrcp0 { get; set; }
        public decimal Dedtaxiss0 { get; set; }
        public decimal Dedtaxoth10 { get; set; }
        public decimal Dedtaxoth20 { get; set; }
        public decimal Cprcoe0 { get; set; }
        public decimal Cpr0 { get; set; }
        public string Tsicod0 { get; set; }
        public string Tsicod1 { get; set; }
        public string Tsicod2 { get; set; }
        public string Tsicod3 { get; set; }
        public string Tsicod4 { get; set; }
        public string Pjt0 { get; set; }
        public decimal Eecincrat0 { get; set; }
        public string Oricry0 { get; set; }
        public string Bpocry0 { get; set; }
        public byte Lineecflg0 { get; set; }
        public byte Linprnflg0 { get; set; }
        public byte Ordflg0 { get; set; }
        public byte Linpstflg0 { get; set; }
        public DateTime Linpstdat0 { get; set; }
        public byte Lininvflg0 { get; set; }
        public string Trsfam0 { get; set; }
        public string Vat0 { get; set; }
        public string Vat1 { get; set; }
        public string Vat2 { get; set; }
        public string Taxrcp0 { get; set; }
        public string Taxiss0 { get; set; }
        public string Taxoth10 { get; set; }
        public string Taxoth20 { get; set; }
        public byte Linpurtyp0 { get; set; }
        public string Satiss0 { get; set; }
        public string Lintex0 { get; set; }
        public string Linstofcy0 { get; set; }
        public byte Stomgtcod0 { get; set; }
        public string Srhnum0 { get; set; }
        public int Srdlin0 { get; set; }
        public byte Linautflg0 { get; set; }
        public byte Lintyp0 { get; set; }
        public byte Lincat0 { get; set; }
        public decimal Likqtycoe0 { get; set; }
        public string Wrh0 { get; set; }
        public string Creusr0 { get; set; }
        public DateTime Credat0 { get; set; }
        public string Updusr0 { get; set; }
        public DateTime Upddat0 { get; set; }
        public DateTime Credattim0 { get; set; }
        public DateTime Upddattim0 { get; set; }
        public byte[] Auuid0 { get; set; }
        public decimal Rowid { get; set; }
    }
}
