using System;
using System.Collections.Generic;

namespace VipcoSageX3.Models.SageX3
{
    public partial class Sorder
    {
        public int Updtick0 { get; set; }
        public string Sohnum0 { get; set; }
        public string Cpy0 { get; set; }
        public string Sohtyp0 { get; set; }
        public byte Sohcat0 { get; set; }
        public string Salfcy0 { get; set; }
        public string Bpcord0 { get; set; }
        public string Bpcinv0 { get; set; }
        public string Bpcpyr0 { get; set; }
        public string Bpapyr0 { get; set; }
        public string Bpcgru0 { get; set; }
        public string Bpaadd0 { get; set; }
        public string Cusordref0 { get; set; }
        public string Pjt0 { get; set; }
        public DateTime Orddat0 { get; set; }
        public DateTime Vlydatcon0 { get; set; }
        public DateTime Shidat0 { get; set; }
        public DateTime Demdlvdat0 { get; set; }
        public DateTime Lndrtndat0 { get; set; }
        public short Daylti0 { get; set; }
        public string Bpcnam0 { get; set; }
        public string Bpcnam1 { get; set; }
        public string Bpaord0 { get; set; }
        public string Bpcaddlig0 { get; set; }
        public string Bpcaddlig1 { get; set; }
        public string Bpcaddlig2 { get; set; }
        public string Bpcposcod0 { get; set; }
        public string Bpccty0 { get; set; }
        public string Bpcsat0 { get; set; }
        public string Bpccry0 { get; set; }
        public string Bpccrynam0 { get; set; }
        public string Cntnam0 { get; set; }
        public string Bpinam0 { get; set; }
        public string Bpinam1 { get; set; }
        public string Bpainv0 { get; set; }
        public string Bpiaddlig0 { get; set; }
        public string Bpiaddlig1 { get; set; }
        public string Bpiaddlig2 { get; set; }
        public string Bpiposcod0 { get; set; }
        public string Bpicty0 { get; set; }
        public string Bpisat0 { get; set; }
        public string Bpicry0 { get; set; }
        public string Bpicrynam0 { get; set; }
        public string Bpieecnum0 { get; set; }
        public string Cninam0 { get; set; }
        public string Bpdnam0 { get; set; }
        public string Bpdnam1 { get; set; }
        public string Bpdaddlig0 { get; set; }
        public string Bpdaddlig1 { get; set; }
        public string Bpdaddlig2 { get; set; }
        public string Bpdposcod0 { get; set; }
        public string Bpdcty0 { get; set; }
        public string Bpdsat0 { get; set; }
        public string Bpdcry0 { get; set; }
        public string Bpdcrynam0 { get; set; }
        public string Cndnam0 { get; set; }
        public string Rep0 { get; set; }
        public string Rep1 { get; set; }
        public string Cur0 { get; set; }
        public byte Chgtyp0 { get; set; }
        public decimal Chgrat0 { get; set; }
        public string Die0 { get; set; }
        public string Die1 { get; set; }
        public string Die2 { get; set; }
        public string Die3 { get; set; }
        public string Die4 { get; set; }
        public string Die5 { get; set; }
        public string Die6 { get; set; }
        public string Die7 { get; set; }
        public string Die8 { get; set; }
        public string Die9 { get; set; }
        public string Die10 { get; set; }
        public string Die11 { get; set; }
        public string Die12 { get; set; }
        public string Die13 { get; set; }
        public string Die14 { get; set; }
        public string Die15 { get; set; }
        public string Die16 { get; set; }
        public string Die17 { get; set; }
        public string Die18 { get; set; }
        public string Die19 { get; set; }
        public string Cce0 { get; set; }
        public string Cce1 { get; set; }
        public string Cce2 { get; set; }
        public string Cce3 { get; set; }
        public string Cce4 { get; set; }
        public string Cce5 { get; set; }
        public string Cce6 { get; set; }
        public string Cce7 { get; set; }
        public string Cce8 { get; set; }
        public string Cce9 { get; set; }
        public string Cce10 { get; set; }
        public string Cce11 { get; set; }
        public string Cce12 { get; set; }
        public string Cce13 { get; set; }
        public string Cce14 { get; set; }
        public string Cce15 { get; set; }
        public string Cce16 { get; set; }
        public string Cce17 { get; set; }
        public string Cce18 { get; set; }
        public string Cce19 { get; set; }
        public string Lan0 { get; set; }
        public string Vacbpr0 { get; set; }
        public string Sstentcod0 { get; set; }
        public string Pte0 { get; set; }
        public string Tsccod0 { get; set; }
        public string Tsccod1 { get; set; }
        public string Tsccod2 { get; set; }
        public string Tsccod3 { get; set; }
        public string Tsccod4 { get; set; }
        public string Dep0 { get; set; }
        public string Bptnum0 { get; set; }
        public string Mdl0 { get; set; }
        public string Stofcy0 { get; set; }
        public byte Drn0 { get; set; }
        public byte Dlvpio0 { get; set; }
        public byte Ordcle0 { get; set; }
        public byte Odl0 { get; set; }
        public byte Dme0 { get; set; }
        public byte Ime0 { get; set; }
        public byte Ocnflg0 { get; set; }
        public byte Ocnprn0 { get; set; }
        public short Copnbr0 { get; set; }
        public string Sohtex10 { get; set; }
        public string Sohtex20 { get; set; }
        public string Sqhnum0 { get; set; }
        public byte Betfcy0 { get; set; }
        public byte Betcpy0 { get; set; }
        public string Orifcy0 { get; set; }
        public string Prfnum0 { get; set; }
        public string Lasdlvnum0 { get; set; }
        public DateTime Lasdlvdat0 { get; set; }
        public string Lasinvnum0 { get; set; }
        public DateTime Lasinvdat0 { get; set; }
        public decimal Invdtaamt0 { get; set; }
        public decimal Invdtaamt1 { get; set; }
        public decimal Invdtaamt2 { get; set; }
        public decimal Invdtaamt3 { get; set; }
        public decimal Invdtaamt4 { get; set; }
        public decimal Invdtaamt5 { get; set; }
        public decimal Invdtaamt6 { get; set; }
        public decimal Invdtaamt7 { get; set; }
        public decimal Invdtaamt8 { get; set; }
        public decimal Invdtaamt9 { get; set; }
        public decimal Invdtaamt10 { get; set; }
        public decimal Invdtaamt11 { get; set; }
        public decimal Invdtaamt12 { get; set; }
        public decimal Invdtaamt13 { get; set; }
        public decimal Invdtaamt14 { get; set; }
        public decimal Invdtaamt15 { get; set; }
        public decimal Invdtaamt16 { get; set; }
        public decimal Invdtaamt17 { get; set; }
        public decimal Invdtaamt18 { get; set; }
        public decimal Invdtaamt19 { get; set; }
        public decimal Invdtaamt20 { get; set; }
        public decimal Invdtaamt21 { get; set; }
        public decimal Invdtaamt22 { get; set; }
        public decimal Invdtaamt23 { get; set; }
        public decimal Invdtaamt24 { get; set; }
        public decimal Invdtaamt25 { get; set; }
        public decimal Invdtaamt26 { get; set; }
        public decimal Invdtaamt27 { get; set; }
        public decimal Invdtaamt28 { get; set; }
        public decimal Invdtaamt29 { get; set; }
        public byte Invdtatyp0 { get; set; }
        public byte Invdtatyp1 { get; set; }
        public byte Invdtatyp2 { get; set; }
        public byte Invdtatyp3 { get; set; }
        public byte Invdtatyp4 { get; set; }
        public byte Invdtatyp5 { get; set; }
        public byte Invdtatyp6 { get; set; }
        public byte Invdtatyp7 { get; set; }
        public byte Invdtatyp8 { get; set; }
        public byte Invdtatyp9 { get; set; }
        public byte Invdtatyp10 { get; set; }
        public byte Invdtatyp11 { get; set; }
        public byte Invdtatyp12 { get; set; }
        public byte Invdtatyp13 { get; set; }
        public byte Invdtatyp14 { get; set; }
        public byte Invdtatyp15 { get; set; }
        public byte Invdtatyp16 { get; set; }
        public byte Invdtatyp17 { get; set; }
        public byte Invdtatyp18 { get; set; }
        public byte Invdtatyp19 { get; set; }
        public byte Invdtatyp20 { get; set; }
        public byte Invdtatyp21 { get; set; }
        public byte Invdtatyp22 { get; set; }
        public byte Invdtatyp23 { get; set; }
        public byte Invdtatyp24 { get; set; }
        public byte Invdtatyp25 { get; set; }
        public byte Invdtatyp26 { get; set; }
        public byte Invdtatyp27 { get; set; }
        public byte Invdtatyp28 { get; set; }
        public byte Invdtatyp29 { get; set; }
        public string Invdtadsp0 { get; set; }
        public string Invdtadsp1 { get; set; }
        public string Invdtadsp2 { get; set; }
        public string Invdtadsp3 { get; set; }
        public string Invdtadsp4 { get; set; }
        public string Invdtadsp5 { get; set; }
        public string Invdtadsp6 { get; set; }
        public string Invdtadsp7 { get; set; }
        public string Invdtadsp8 { get; set; }
        public string Invdtadsp9 { get; set; }
        public string Invdtadsp10 { get; set; }
        public string Invdtadsp11 { get; set; }
        public string Invdtadsp12 { get; set; }
        public string Invdtadsp13 { get; set; }
        public string Invdtadsp14 { get; set; }
        public string Invdtadsp15 { get; set; }
        public string Invdtadsp16 { get; set; }
        public string Invdtadsp17 { get; set; }
        public string Invdtadsp18 { get; set; }
        public string Invdtadsp19 { get; set; }
        public string Invdtadsp20 { get; set; }
        public string Invdtadsp21 { get; set; }
        public string Invdtadsp22 { get; set; }
        public string Invdtadsp23 { get; set; }
        public string Invdtadsp24 { get; set; }
        public string Invdtadsp25 { get; set; }
        public string Invdtadsp26 { get; set; }
        public string Invdtadsp27 { get; set; }
        public string Invdtadsp28 { get; set; }
        public string Invdtadsp29 { get; set; }
        public short Invdta0 { get; set; }
        public short Invdta1 { get; set; }
        public short Invdta2 { get; set; }
        public short Invdta3 { get; set; }
        public short Invdta4 { get; set; }
        public short Invdta5 { get; set; }
        public short Invdta6 { get; set; }
        public short Invdta7 { get; set; }
        public short Invdta8 { get; set; }
        public short Invdta9 { get; set; }
        public short Invdta10 { get; set; }
        public short Invdta11 { get; set; }
        public short Invdta12 { get; set; }
        public short Invdta13 { get; set; }
        public short Invdta14 { get; set; }
        public short Invdta15 { get; set; }
        public short Invdta16 { get; set; }
        public short Invdta17 { get; set; }
        public short Invdta18 { get; set; }
        public short Invdta19 { get; set; }
        public short Invdta20 { get; set; }
        public short Invdta21 { get; set; }
        public short Invdta22 { get; set; }
        public short Invdta23 { get; set; }
        public short Invdta24 { get; set; }
        public short Invdta25 { get; set; }
        public short Invdta26 { get; set; }
        public short Invdta27 { get; set; }
        public short Invdta28 { get; set; }
        public short Invdta29 { get; set; }
        public string Sfisstcod0 { get; set; }
        public string Sfisstcod1 { get; set; }
        public string Sfisstcod2 { get; set; }
        public string Sfisstcod3 { get; set; }
        public string Sfisstcod4 { get; set; }
        public string Sfisstcod5 { get; set; }
        public string Sfisstcod6 { get; set; }
        public string Sfisstcod7 { get; set; }
        public string Sfisstcod8 { get; set; }
        public string Sfisstcod9 { get; set; }
        public string Sfisstcod10 { get; set; }
        public string Sfisstcod11 { get; set; }
        public string Sfisstcod12 { get; set; }
        public string Sfisstcod13 { get; set; }
        public string Sfisstcod14 { get; set; }
        public string Sfisstcod15 { get; set; }
        public string Sfisstcod16 { get; set; }
        public string Sfisstcod17 { get; set; }
        public string Sfisstcod18 { get; set; }
        public string Sfisstcod19 { get; set; }
        public string Sfisstcod20 { get; set; }
        public string Sfisstcod21 { get; set; }
        public string Sfisstcod22 { get; set; }
        public string Sfisstcod23 { get; set; }
        public string Sfisstcod24 { get; set; }
        public string Sfisstcod25 { get; set; }
        public string Sfisstcod26 { get; set; }
        public string Sfisstcod27 { get; set; }
        public string Sfisstcod28 { get; set; }
        public string Sfisstcod29 { get; set; }
        public byte Prityp0 { get; set; }
        public decimal Ordnot0 { get; set; }
        public decimal Ordati0 { get; set; }
        public decimal Ordnotl0 { get; set; }
        public decimal Ordatil0 { get; set; }
        public decimal Ordinvnot0 { get; set; }
        public decimal Ordinvati0 { get; set; }
        public decimal Ordinvnotl0 { get; set; }
        public decimal Ordinvatil0 { get; set; }
        public decimal Dlrnot0 { get; set; }
        public decimal Dlrati0 { get; set; }
        public decimal Pfmtot0 { get; set; }
        public byte Discrgtyp0 { get; set; }
        public byte Discrgtyp1 { get; set; }
        public byte Discrgtyp2 { get; set; }
        public byte Discrgtyp3 { get; set; }
        public byte Discrgtyp4 { get; set; }
        public byte Discrgtyp5 { get; set; }
        public byte Discrgtyp6 { get; set; }
        public byte Discrgtyp7 { get; set; }
        public byte Discrgtyp8 { get; set; }
        public short Invdtalin0 { get; set; }
        public short Invdtalin1 { get; set; }
        public short Invdtalin2 { get; set; }
        public short Invdtalin3 { get; set; }
        public short Invdtalin4 { get; set; }
        public short Invdtalin5 { get; set; }
        public short Invdtalin6 { get; set; }
        public short Invdtalin7 { get; set; }
        public short Invdtalin8 { get; set; }
        public byte Alltyp0 { get; set; }
        public byte Unl0 { get; set; }
        public short Linnbr0 { get; set; }
        public short Clelinnbr0 { get; set; }
        public short Alllinnbr0 { get; set; }
        public short Dlvlinnbr0 { get; set; }
        public short Invlinnbr0 { get; set; }
        public byte Ordsta0 { get; set; }
        public byte Allsta0 { get; set; }
        public byte Dlvsta0 { get; set; }
        public byte Invsta0 { get; set; }
        public byte Cdtsta0 { get; set; }
        public byte Appflg0 { get; set; }
        public short Revnum0 { get; set; }
        public string Shiadecod0 { get; set; }
        public string Eecict0 { get; set; }
        public byte Eecloc0 { get; set; }
        public string Ictcty0 { get; set; }
        public string Ffwnum0 { get; set; }
        public string Ffwadd0 { get; set; }
        public string Geocod0 { get; set; }
        public string Insctyflg0 { get; set; }
        public string Vtt0 { get; set; }
        public decimal Amttax0 { get; set; }
        public decimal Bastax0 { get; set; }
        public string Cclren0 { get; set; }
        public DateTime Ccldat0 { get; set; }
        public string Srenum0 { get; set; }
        public string Cmgnum0 { get; set; }
        public string Opgnum0 { get; set; }
        public string Opgtyp0 { get; set; }
        public string Plistc0 { get; set; }
        public int Expnum0 { get; set; }
        public string Sinum0 { get; set; }
        public decimal Dsptotqty0 { get; set; }
        public decimal Dsptotwei0 { get; set; }
        public decimal Dsptotvol0 { get; set; }
        public string Dspweu0 { get; set; }
        public string Dspvou0 { get; set; }
        public string Sdhtyp0 { get; set; }
        public string Creusr0 { get; set; }
        public DateTime Credat0 { get; set; }
        public string Updusr0 { get; set; }
        public DateTime Upddat0 { get; set; }
        public byte Hldsta0 { get; set; }
        public string Hldcod0 { get; set; }
        public string Hldusr0 { get; set; }
        public DateTime Hlddat0 { get; set; }
        public string Hldtim0 { get; set; }
        public string Hldcodp0 { get; set; }
        public string Hldusrp0 { get; set; }
        public DateTime Hlddatp0 { get; set; }
        public string Hldtimp0 { get; set; }
        public byte Cdtstap0 { get; set; }
        public byte Adrval0 { get; set; }
        public string Demdlvhou0 { get; set; }
        public DateTime Credattim0 { get; set; }
        public DateTime Upddattim0 { get; set; }
        public byte[] Auuid0 { get; set; }
        public string Invcnd0 { get; set; }
        public DateTime Vcrinvcnddat0 { get; set; }
        public decimal Inrnot0 { get; set; }
        public decimal Inrati0 { get; set; }
        public decimal Inrschnot0 { get; set; }
        public decimal Inrschati0 { get; set; }
        public decimal Rowid { get; set; }
    }
}
