using System;
using System.Collections.Generic;

namespace VipcoSageX3.Models.SageX3
{
    public partial class Stojou
    {
        public int Updtick0 { get; set; }
        public string Stofcy0 { get; set; }
        public byte Updcod0 { get; set; }
        public string Itmref0 { get; set; }
        public DateTime Iptdat0 { get; set; }
        public int Mvtseq0 { get; set; }
        public int Mvtind0 { get; set; }
        public DateTime Cstdat0 { get; set; }
        public string Csttim0 { get; set; }
        public decimal Cstcou0 { get; set; }
        public string Owner0 { get; set; }
        public string Lot0 { get; set; }
        public string Slo0 { get; set; }
        public string Bpslot0 { get; set; }
        public string Loc0 { get; set; }
        public string Wrh0 { get; set; }
        public string Sernum0 { get; set; }
        public byte Trstyp0 { get; set; }
        public string Trsfam0 { get; set; }
        public string Mvtdes0 { get; set; }
        public string Pjt0 { get; set; }
        public string Bprnum0 { get; set; }
        public byte Vcrtyp0 { get; set; }
        public string Vcrnum0 { get; set; }
        public int Vcrlin0 { get; set; }
        public byte Vcrtypori0 { get; set; }
        public string Vcrnumori0 { get; set; }
        public int Vcrlinori0 { get; set; }
        public int Vcrseqori0 { get; set; }
        public byte Vcrtypreg0 { get; set; }
        public string Vcrnumreg0 { get; set; }
        public int Vcrlinreg0 { get; set; }
        public string Usrfld10 { get; set; }
        public string Usrfld20 { get; set; }
        public decimal Usrfld30 { get; set; }
        public DateTime Usrfld40 { get; set; }
        public string Pcu0 { get; set; }
        public decimal Qtypcu0 { get; set; }
        public decimal Pcustucoe0 { get; set; }
        public decimal Qtystu0 { get; set; }
        public string Stu0 { get; set; }
        public string Pcuori0 { get; set; }
        public decimal Pcustuori0 { get; set; }
        public decimal Amtord0 { get; set; }
        public decimal Amtval0 { get; set; }
        public decimal Varord0 { get; set; }
        public decimal Varval0 { get; set; }
        public decimal Priord0 { get; set; }
        public decimal Prival0 { get; set; }
        public byte Prinat0 { get; set; }
        public decimal Amtval20 { get; set; }
        public decimal Varval20 { get; set; }
        public decimal Prival20 { get; set; }
        public byte Prinat20 { get; set; }
        public byte Priregflg0 { get; set; }
        public decimal Amtdev0 { get; set; }
        public decimal Amtdev20 { get; set; }
        public DateTime Shldat0 { get; set; }
        public string Sta0 { get; set; }
        public decimal Pot0 { get; set; }
        public decimal Act0 { get; set; }
        public decimal Actqty0 { get; set; }
        public string Qlyctldem0 { get; set; }
        public byte Prnflg0 { get; set; }
        public byte Regflg0 { get; set; }
        public string Lbefmt0 { get; set; }
        public short Lbenbr0 { get; set; }
        public string Die0 { get; set; }
        public string Die1 { get; set; }
        public string Die2 { get; set; }
        public string Die3 { get; set; }
        public string Die4 { get; set; }
        public string Die5 { get; set; }
        public string Die6 { get; set; }
        public string Die7 { get; set; }
        public string Die8 { get; set; }
        public string Die9 { get; set; }
        public string Die10 { get; set; }
        public string Die11 { get; set; }
        public string Die12 { get; set; }
        public string Die13 { get; set; }
        public string Die14 { get; set; }
        public string Die15 { get; set; }
        public string Die16 { get; set; }
        public string Die17 { get; set; }
        public string Die18 { get; set; }
        public string Die19 { get; set; }
        public string Cce0 { get; set; }
        public string Cce1 { get; set; }
        public string Cce2 { get; set; }
        public string Cce3 { get; set; }
        public string Cce4 { get; set; }
        public string Cce5 { get; set; }
        public string Cce6 { get; set; }
        public string Cce7 { get; set; }
        public string Cce8 { get; set; }
        public string Cce9 { get; set; }
        public string Cce10 { get; set; }
        public string Cce11 { get; set; }
        public string Cce12 { get; set; }
        public string Cce13 { get; set; }
        public string Cce14 { get; set; }
        public string Cce15 { get; set; }
        public string Cce16 { get; set; }
        public string Cce17 { get; set; }
        public string Cce18 { get; set; }
        public string Cce19 { get; set; }
        public string Entcod0 { get; set; }
        public string Finrspfcy0 { get; set; }
        public byte Aggifaflg0 { get; set; }
        public string Gte0 { get; set; }
        public string Numvcr0 { get; set; }
        public string Palnum0 { get; set; }
        public string Ctrnum0 { get; set; }
        public byte Betcpy0 { get; set; }
        public DateTime Dludat0 { get; set; }
        public DateTime Newltidat0 { get; set; }
        public DateTime Cremvtdat0 { get; set; }
        public string Cremvttim0 { get; set; }
        public int Cremvtseq0 { get; set; }
        public int Expnum0 { get; set; }
        public int Pronum0 { get; set; }
        public DateTime Credat0 { get; set; }
        public string Cretim0 { get; set; }
        public string Creusr0 { get; set; }
        public DateTime Upddat0 { get; set; }
        public string Updusr0 { get; set; }
        public DateTime Credattim0 { get; set; }
        public DateTime Upddattim0 { get; set; }
        public byte[] Auuid0 { get; set; }
        public DateTime Accdat0 { get; set; }
        public string Eccvalmaj0 { get; set; }
        public string Eccvalmin0 { get; set; }
        public string Stofld10 { get; set; }
        public string Stofld20 { get; set; }
        public decimal Zsm010 { get; set; }
        public decimal Zsm020 { get; set; }
        public decimal Rowid { get; set; }
    }
}
