using System;
using System.Collections.Generic;

namespace VipcoSageX3.Models.SageX3
{
    public partial class Uporder
    {
        public int Updtick0 { get; set; }
        public string Pohnum0 { get; set; }
        public string Cpy0 { get; set; }
        public string Pohfcy0 { get; set; }
        public byte Pohtyp0 { get; set; }
        public byte Purtyp0 { get; set; }
        public short Revnum0 { get; set; }
        public string Revcod0 { get; set; }
        public DateTime Orddat0 { get; set; }
        public string Ordref0 { get; set; }
        public string Bpsnum0 { get; set; }
        public string Bpaadd0 { get; set; }
        public string Bprnam0 { get; set; }
        public string Bprnam1 { get; set; }
        public string Bpaaddlig0 { get; set; }
        public string Bpaaddlig1 { get; set; }
        public string Bpaaddlig2 { get; set; }
        public string Poscod0 { get; set; }
        public string Cty0 { get; set; }
        public string Sat0 { get; set; }
        public string Cry0 { get; set; }
        public string Crynam0 { get; set; }
        public string Bpoadd0 { get; set; }
        public string Bponam0 { get; set; }
        public string Bponam1 { get; set; }
        public string Bpoaddlig0 { get; set; }
        public string Bpoaddlig1 { get; set; }
        public string Bpoaddlig2 { get; set; }
        public string Bpoposcod0 { get; set; }
        public string Bpocty0 { get; set; }
        public string Bposat0 { get; set; }
        public string Bpocry0 { get; set; }
        public string Bpocrynam0 { get; set; }
        public string Invfcy0 { get; set; }
        public string Rcpfcy0 { get; set; }
        public DateTime Extrcpdat10 { get; set; }
        public string Tsscod0 { get; set; }
        public string Tsscod1 { get; set; }
        public string Tsscod2 { get; set; }
        public string Tsscod3 { get; set; }
        public string Tsscod4 { get; set; }
        public string Pte0 { get; set; }
        public string Mdl0 { get; set; }
        public string Bptnum0 { get; set; }
        public string Bprpay0 { get; set; }
        public string Bpapay0 { get; set; }
        public string Bpsinv0 { get; set; }
        public string Bpainv0 { get; set; }
        public string Eecict0 { get; set; }
        public string Ictcty0 { get; set; }
        public string Gpgcod0 { get; set; }
        public string Ffwnum0 { get; set; }
        public string Ffwadd0 { get; set; }
        public byte Eecloc0 { get; set; }
        public string Eecnum0 { get; set; }
        public string Buy0 { get; set; }
        public string Die0 { get; set; }
        public string Die1 { get; set; }
        public string Die2 { get; set; }
        public string Die3 { get; set; }
        public string Die4 { get; set; }
        public string Die5 { get; set; }
        public string Die6 { get; set; }
        public string Die7 { get; set; }
        public string Die8 { get; set; }
        public string Die9 { get; set; }
        public string Die10 { get; set; }
        public string Die11 { get; set; }
        public string Die12 { get; set; }
        public string Die13 { get; set; }
        public string Die14 { get; set; }
        public string Die15 { get; set; }
        public string Die16 { get; set; }
        public string Die17 { get; set; }
        public string Die18 { get; set; }
        public string Die19 { get; set; }
        public string Cce0 { get; set; }
        public string Cce1 { get; set; }
        public string Cce2 { get; set; }
        public string Cce3 { get; set; }
        public string Cce4 { get; set; }
        public string Cce5 { get; set; }
        public string Cce6 { get; set; }
        public string Cce7 { get; set; }
        public string Cce8 { get; set; }
        public string Cce9 { get; set; }
        public string Cce10 { get; set; }
        public string Cce11 { get; set; }
        public string Cce12 { get; set; }
        public string Cce13 { get; set; }
        public string Cce14 { get; set; }
        public string Cce15 { get; set; }
        public string Cce16 { get; set; }
        public string Cce17 { get; set; }
        public string Cce18 { get; set; }
        public string Cce19 { get; set; }
        public string Lan0 { get; set; }
        public string Cur0 { get; set; }
        public byte Chgtyp0 { get; set; }
        public decimal Chgcoe0 { get; set; }
        public string Vacbpr0 { get; set; }
        public short Vactyp0 { get; set; }
        public byte Discrgtyp0 { get; set; }
        public byte Discrgtyp1 { get; set; }
        public byte Discrgtyp2 { get; set; }
        public byte Discrgtyp3 { get; set; }
        public byte Discrgtyp4 { get; set; }
        public byte Discrgtyp5 { get; set; }
        public byte Discrgtyp6 { get; set; }
        public byte Discrgtyp7 { get; set; }
        public byte Discrgtyp8 { get; set; }
        public short Linnbr0 { get; set; }
        public short Fbulinnbr0 { get; set; }
        public short Rcplinnbr0 { get; set; }
        public short Clelinnbr0 { get; set; }
        public short Invlinnbr0 { get; set; }
        public int Rcpnbr0 { get; set; }
        public int Invnbr0 { get; set; }
        public byte Appflg0 { get; set; }
        public byte Cleflg0 { get; set; }
        public byte Rcpflg0 { get; set; }
        public byte Invflg0 { get; set; }
        public byte Prnflg0 { get; set; }
        public short Copnbr0 { get; set; }
        public string Tex10 { get; set; }
        public string Tex20 { get; set; }
        public DateTime Ocndat0 { get; set; }
        public string Ocnnum0 { get; set; }
        public string Ocnrem0 { get; set; }
        public byte Ocnflg0 { get; set; }
        public byte Fupflg0 { get; set; }
        public byte Betcpy0 { get; set; }
        public byte Betfcy0 { get; set; }
        public string Orifcy0 { get; set; }
        public string Stofcy0 { get; set; }
        public string Salfcy0 { get; set; }
        public byte Sohcat0 { get; set; }
        public string Bpcord0 { get; set; }
        public byte Dme0 { get; set; }
        public string Dspweu0 { get; set; }
        public string Dspvou0 { get; set; }
        public decimal Totlinati0 { get; set; }
        public decimal Totlinamt0 { get; set; }
        public decimal Totlinqty0 { get; set; }
        public decimal Totlinweu0 { get; set; }
        public decimal Totlinvou0 { get; set; }
        public decimal Tottaxamt0 { get; set; }
        public short Invdtalin10 { get; set; }
        public short Invdtalin11 { get; set; }
        public short Invdtalin12 { get; set; }
        public short Invdtalin13 { get; set; }
        public short Invdtalin14 { get; set; }
        public short Invdtalin15 { get; set; }
        public short Invdtalin16 { get; set; }
        public short Invdtalin17 { get; set; }
        public short Invdtalin18 { get; set; }
        public string Invdtavat10 { get; set; }
        public string Invdtavat11 { get; set; }
        public string Invdtavat12 { get; set; }
        public string Invdtavat13 { get; set; }
        public string Invdtavat14 { get; set; }
        public string Invdtavat15 { get; set; }
        public string Invdtavat16 { get; set; }
        public string Invdtavat17 { get; set; }
        public string Invdtavat18 { get; set; }
        public short Invdtalin20 { get; set; }
        public short Invdtalin21 { get; set; }
        public short Invdtalin22 { get; set; }
        public short Invdtalin23 { get; set; }
        public short Invdtalin24 { get; set; }
        public short Invdtalin25 { get; set; }
        public short Invdtalin26 { get; set; }
        public short Invdtalin27 { get; set; }
        public short Invdtalin28 { get; set; }
        public string Invdtavat20 { get; set; }
        public string Invdtavat21 { get; set; }
        public string Invdtavat22 { get; set; }
        public string Invdtavat23 { get; set; }
        public string Invdtavat24 { get; set; }
        public string Invdtavat25 { get; set; }
        public string Invdtavat26 { get; set; }
        public string Invdtavat27 { get; set; }
        public string Invdtavat28 { get; set; }
        public decimal Totord0 { get; set; }
        public decimal Ttvord0 { get; set; }
        public decimal Totordl0 { get; set; }
        public decimal Ttvordl0 { get; set; }
        public decimal Totvlt0 { get; set; }
        public DateTime Strdat0 { get; set; }
        public DateTime Enddat0 { get; set; }
        public int Expnum0 { get; set; }
        public string Creusr0 { get; set; }
        public DateTime Credat0 { get; set; }
        public string Updusr0 { get; set; }
        public DateTime Upddat0 { get; set; }
        public DateTime Credattim0 { get; set; }
        public DateTime Upddattim0 { get; set; }
        public byte[] Auuid0 { get; set; }
        public decimal Rowid { get; set; }
    }
}
